// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: binding_table_variable_def.proto

package ast

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BindingTableVariableDef struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Todo *Todo                  `protobuf:"bytes,1,opt,name=todo"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BindingTableVariableDef) Reset() {
	*x = BindingTableVariableDef{}
	mi := &file_binding_table_variable_def_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindingTableVariableDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingTableVariableDef) ProtoMessage() {}

func (x *BindingTableVariableDef) ProtoReflect() protoreflect.Message {
	mi := &file_binding_table_variable_def_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BindingTableVariableDef) GetTodo() *Todo {
	if x != nil {
		return x.xxx_hidden_Todo
	}
	return nil
}

func (x *BindingTableVariableDef) SetTodo(v *Todo) {
	x.xxx_hidden_Todo = v
}

func (x *BindingTableVariableDef) HasTodo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Todo != nil
}

func (x *BindingTableVariableDef) ClearTodo() {
	x.xxx_hidden_Todo = nil
}

type BindingTableVariableDef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Todo *Todo
}

func (b0 BindingTableVariableDef_builder) Build() *BindingTableVariableDef {
	m0 := &BindingTableVariableDef{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Todo = b.Todo
	return m0
}

var File_binding_table_variable_def_proto protoreflect.FileDescriptor

var file_binding_table_variable_def_proto_rawDesc = string([]byte{
	0x0a, 0x20, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f,
	0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x64, 0x65, 0x66, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x61, 0x73, 0x74, 0x1a, 0x21, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x5f, 0x66, 0x65, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x74, 0x6f, 0x64, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x17, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65,
	0x66, 0x12, 0x1d, 0x0a, 0x04, 0x74, 0x6f, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x52, 0x04, 0x74, 0x6f, 0x64, 0x6f,
	0x42, 0x10, 0x5a, 0x04, 0x2f, 0x61, 0x73, 0x74, 0x92, 0x03, 0x07, 0xd2, 0x3e, 0x02, 0x10, 0x03,
	0x08, 0x02, 0x62, 0x08, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x70, 0xe8, 0x07,
})

var file_binding_table_variable_def_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_binding_table_variable_def_proto_goTypes = []any{
	(*BindingTableVariableDef)(nil), // 0: ast.BindingTableVariableDef
	(*Todo)(nil),                    // 1: ast.Todo
}
var file_binding_table_variable_def_proto_depIdxs = []int32{
	1, // 0: ast.BindingTableVariableDef.todo:type_name -> ast.Todo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_binding_table_variable_def_proto_init() }
func file_binding_table_variable_def_proto_init() {
	if File_binding_table_variable_def_proto != nil {
		return
	}
	file_todo_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_binding_table_variable_def_proto_rawDesc), len(file_binding_table_variable_def_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_binding_table_variable_def_proto_goTypes,
		DependencyIndexes: file_binding_table_variable_def_proto_depIdxs,
		MessageInfos:      file_binding_table_variable_def_proto_msgTypes,
	}.Build()
	File_binding_table_variable_def_proto = out.File
	file_binding_table_variable_def_proto_goTypes = nil
	file_binding_table_variable_def_proto_depIdxs = nil
}
