// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: catalog_modifying_statement.proto

package ast

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LinearCatalogModifyingStatement struct {
	state                 protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_Statements *[]*CatalogModifyingStatement `protobuf:"bytes,1,rep,name=statements"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *LinearCatalogModifyingStatement) Reset() {
	*x = LinearCatalogModifyingStatement{}
	mi := &file_catalog_modifying_statement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinearCatalogModifyingStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinearCatalogModifyingStatement) ProtoMessage() {}

func (x *LinearCatalogModifyingStatement) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_modifying_statement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LinearCatalogModifyingStatement) GetStatements() []*CatalogModifyingStatement {
	if x != nil {
		if x.xxx_hidden_Statements != nil {
			return *x.xxx_hidden_Statements
		}
	}
	return nil
}

func (x *LinearCatalogModifyingStatement) SetStatements(v []*CatalogModifyingStatement) {
	x.xxx_hidden_Statements = &v
}

type LinearCatalogModifyingStatement_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Statements []*CatalogModifyingStatement
}

func (b0 LinearCatalogModifyingStatement_builder) Build() *LinearCatalogModifyingStatement {
	m0 := &LinearCatalogModifyingStatement{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Statements = &b.Statements
	return m0
}

type CatalogModifyingStatement struct {
	state           protoimpl.MessageState           `protogen:"opaque.v1"`
	xxx_hidden_Type isCatalogModifyingStatement_Type `protobuf_oneof:"type"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CatalogModifyingStatement) Reset() {
	*x = CatalogModifyingStatement{}
	mi := &file_catalog_modifying_statement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogModifyingStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogModifyingStatement) ProtoMessage() {}

func (x *CatalogModifyingStatement) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_modifying_statement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CatalogModifyingStatement) GetCreateGraphStatement() *CreateGraphStatement {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*catalogModifyingStatement_CreateGraphStatement); ok {
			return x.CreateGraphStatement
		}
	}
	return nil
}

func (x *CatalogModifyingStatement) GetDropGraphStatement() *DropGraphStatement {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*catalogModifyingStatement_DropGraphStatement); ok {
			return x.DropGraphStatement
		}
	}
	return nil
}

func (x *CatalogModifyingStatement) SetCreateGraphStatement(v *CreateGraphStatement) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &catalogModifyingStatement_CreateGraphStatement{v}
}

func (x *CatalogModifyingStatement) SetDropGraphStatement(v *DropGraphStatement) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &catalogModifyingStatement_DropGraphStatement{v}
}

func (x *CatalogModifyingStatement) HasType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Type != nil
}

func (x *CatalogModifyingStatement) HasCreateGraphStatement() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*catalogModifyingStatement_CreateGraphStatement)
	return ok
}

func (x *CatalogModifyingStatement) HasDropGraphStatement() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*catalogModifyingStatement_DropGraphStatement)
	return ok
}

func (x *CatalogModifyingStatement) ClearType() {
	x.xxx_hidden_Type = nil
}

func (x *CatalogModifyingStatement) ClearCreateGraphStatement() {
	if _, ok := x.xxx_hidden_Type.(*catalogModifyingStatement_CreateGraphStatement); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *CatalogModifyingStatement) ClearDropGraphStatement() {
	if _, ok := x.xxx_hidden_Type.(*catalogModifyingStatement_DropGraphStatement); ok {
		x.xxx_hidden_Type = nil
	}
}

const CatalogModifyingStatement_Type_not_set_case case_CatalogModifyingStatement_Type = 0
const CatalogModifyingStatement_CreateGraphStatement_case case_CatalogModifyingStatement_Type = 1
const CatalogModifyingStatement_DropGraphStatement_case case_CatalogModifyingStatement_Type = 2

func (x *CatalogModifyingStatement) WhichType() case_CatalogModifyingStatement_Type {
	if x == nil {
		return CatalogModifyingStatement_Type_not_set_case
	}
	switch x.xxx_hidden_Type.(type) {
	case *catalogModifyingStatement_CreateGraphStatement:
		return CatalogModifyingStatement_CreateGraphStatement_case
	case *catalogModifyingStatement_DropGraphStatement:
		return CatalogModifyingStatement_DropGraphStatement_case
	default:
		return CatalogModifyingStatement_Type_not_set_case
	}
}

type CatalogModifyingStatement_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Type:
	CreateGraphStatement *CreateGraphStatement
	DropGraphStatement   *DropGraphStatement
	// -- end of xxx_hidden_Type
}

func (b0 CatalogModifyingStatement_builder) Build() *CatalogModifyingStatement {
	m0 := &CatalogModifyingStatement{}
	b, x := &b0, m0
	_, _ = b, x
	if b.CreateGraphStatement != nil {
		x.xxx_hidden_Type = &catalogModifyingStatement_CreateGraphStatement{b.CreateGraphStatement}
	}
	if b.DropGraphStatement != nil {
		x.xxx_hidden_Type = &catalogModifyingStatement_DropGraphStatement{b.DropGraphStatement}
	}
	return m0
}

type case_CatalogModifyingStatement_Type protoreflect.FieldNumber

func (x case_CatalogModifyingStatement_Type) String() string {
	md := file_catalog_modifying_statement_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isCatalogModifyingStatement_Type interface {
	isCatalogModifyingStatement_Type()
}

type catalogModifyingStatement_CreateGraphStatement struct {
	CreateGraphStatement *CreateGraphStatement `protobuf:"bytes,1,opt,name=create_graph_statement,json=createGraphStatement,oneof"`
}

type catalogModifyingStatement_DropGraphStatement struct {
	DropGraphStatement *DropGraphStatement `protobuf:"bytes,2,opt,name=drop_graph_statement,json=dropGraphStatement,oneof"`
}

func (*catalogModifyingStatement_CreateGraphStatement) isCatalogModifyingStatement_Type() {}

func (*catalogModifyingStatement_DropGraphStatement) isCatalogModifyingStatement_Type() {}

type CreateGraphStatement struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_IfNotExists   bool                   `protobuf:"varint,1,opt,name=if_not_exists,json=ifNotExists"`
	xxx_hidden_ReplaceGraph  bool                   `protobuf:"varint,2,opt,name=replace_graph,json=replaceGraph"`
	xxx_hidden_ParentAndName *CatalogParentAndName  `protobuf:"bytes,3,opt,name=parent_and_name,json=parentAndName"`
	xxx_hidden_GraphType     *GraphType             `protobuf:"bytes,4,opt,name=graph_type,json=graphType"`
	xxx_hidden_GraphSource   *GraphExpression       `protobuf:"bytes,5,opt,name=graph_source,json=graphSource"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CreateGraphStatement) Reset() {
	*x = CreateGraphStatement{}
	mi := &file_catalog_modifying_statement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGraphStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGraphStatement) ProtoMessage() {}

func (x *CreateGraphStatement) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_modifying_statement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateGraphStatement) GetIfNotExists() bool {
	if x != nil {
		return x.xxx_hidden_IfNotExists
	}
	return false
}

func (x *CreateGraphStatement) GetReplaceGraph() bool {
	if x != nil {
		return x.xxx_hidden_ReplaceGraph
	}
	return false
}

func (x *CreateGraphStatement) GetParentAndName() *CatalogParentAndName {
	if x != nil {
		return x.xxx_hidden_ParentAndName
	}
	return nil
}

func (x *CreateGraphStatement) GetGraphType() *GraphType {
	if x != nil {
		return x.xxx_hidden_GraphType
	}
	return nil
}

func (x *CreateGraphStatement) GetGraphSource() *GraphExpression {
	if x != nil {
		return x.xxx_hidden_GraphSource
	}
	return nil
}

func (x *CreateGraphStatement) SetIfNotExists(v bool) {
	x.xxx_hidden_IfNotExists = v
}

func (x *CreateGraphStatement) SetReplaceGraph(v bool) {
	x.xxx_hidden_ReplaceGraph = v
}

func (x *CreateGraphStatement) SetParentAndName(v *CatalogParentAndName) {
	x.xxx_hidden_ParentAndName = v
}

func (x *CreateGraphStatement) SetGraphType(v *GraphType) {
	x.xxx_hidden_GraphType = v
}

func (x *CreateGraphStatement) SetGraphSource(v *GraphExpression) {
	x.xxx_hidden_GraphSource = v
}

func (x *CreateGraphStatement) HasParentAndName() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ParentAndName != nil
}

func (x *CreateGraphStatement) HasGraphType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_GraphType != nil
}

func (x *CreateGraphStatement) HasGraphSource() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_GraphSource != nil
}

func (x *CreateGraphStatement) ClearParentAndName() {
	x.xxx_hidden_ParentAndName = nil
}

func (x *CreateGraphStatement) ClearGraphType() {
	x.xxx_hidden_GraphType = nil
}

func (x *CreateGraphStatement) ClearGraphSource() {
	x.xxx_hidden_GraphSource = nil
}

type CreateGraphStatement_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	IfNotExists   bool
	ReplaceGraph  bool
	ParentAndName *CatalogParentAndName
	GraphType     *GraphType
	GraphSource   *GraphExpression
}

func (b0 CreateGraphStatement_builder) Build() *CreateGraphStatement {
	m0 := &CreateGraphStatement{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_IfNotExists = b.IfNotExists
	x.xxx_hidden_ReplaceGraph = b.ReplaceGraph
	x.xxx_hidden_ParentAndName = b.ParentAndName
	x.xxx_hidden_GraphType = b.GraphType
	x.xxx_hidden_GraphSource = b.GraphSource
	return m0
}

type DropGraphStatement struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_IfExists      bool                   `protobuf:"varint,1,opt,name=if_exists,json=ifExists"`
	xxx_hidden_ParentAndName *CatalogParentAndName  `protobuf:"bytes,2,opt,name=parent_and_name,json=parentAndName"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *DropGraphStatement) Reset() {
	*x = DropGraphStatement{}
	mi := &file_catalog_modifying_statement_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropGraphStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropGraphStatement) ProtoMessage() {}

func (x *DropGraphStatement) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_modifying_statement_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DropGraphStatement) GetIfExists() bool {
	if x != nil {
		return x.xxx_hidden_IfExists
	}
	return false
}

func (x *DropGraphStatement) GetParentAndName() *CatalogParentAndName {
	if x != nil {
		return x.xxx_hidden_ParentAndName
	}
	return nil
}

func (x *DropGraphStatement) SetIfExists(v bool) {
	x.xxx_hidden_IfExists = v
}

func (x *DropGraphStatement) SetParentAndName(v *CatalogParentAndName) {
	x.xxx_hidden_ParentAndName = v
}

func (x *DropGraphStatement) HasParentAndName() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ParentAndName != nil
}

func (x *DropGraphStatement) ClearParentAndName() {
	x.xxx_hidden_ParentAndName = nil
}

type DropGraphStatement_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	IfExists      bool
	ParentAndName *CatalogParentAndName
}

func (b0 DropGraphStatement_builder) Build() *DropGraphStatement {
	m0 := &DropGraphStatement{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_IfExists = b.IfExists
	x.xxx_hidden_ParentAndName = b.ParentAndName
	return m0
}

var File_catalog_modifying_statement_proto protoreflect.FileDescriptor

var file_catalog_modifying_statement_proto_rawDesc = string([]byte{
	0x0a, 0x21, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79,
	0x69, 0x6e, 0x67, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x73, 0x74, 0x1a, 0x21, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x5f, 0x66, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x63, 0x61, 0x74,
	0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x67, 0x72, 0x61, 0x70,
	0x68, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x67, 0x72,
	0x61, 0x70, 0x68, 0x5f, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x61, 0x0a, 0x1f, 0x4c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x43, 0x61,
	0x74, 0x61, 0x6c, 0x6f, 0x67, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x69, 0x6e, 0x67, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3e, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x73,
	0x74, 0x2e, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x69,
	0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0xc3, 0x01, 0x0a, 0x19, 0x43, 0x61, 0x74, 0x61,
	0x6c, 0x6f, 0x67, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x51, 0x0a, 0x16, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f,
	0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x47, 0x72, 0x61, 0x70, 0x68, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x48, 0x00, 0x52, 0x14, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x61, 0x70, 0x68, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x4b, 0x0a, 0x14, 0x64, 0x72, 0x6f, 0x70,
	0x5f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x44, 0x72, 0x6f,
	0x70, 0x47, 0x72, 0x61, 0x70, 0x68, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x48,
	0x00, 0x52, 0x12, 0x64, 0x72, 0x6f, 0x70, 0x47, 0x72, 0x61, 0x70, 0x68, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x98, 0x02,
	0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x61, 0x70, 0x68, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x69, 0x66, 0x5f, 0x6e, 0x6f, 0x74,
	0x5f, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69,
	0x66, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65,
	0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0c, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x47, 0x72, 0x61, 0x70, 0x68, 0x12,
	0x41, 0x0a, 0x0f, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x6e, 0x64, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x43,
	0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x4e,
	0x61, 0x6d, 0x65, 0x52, 0x0d, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x34, 0x0a, 0x0a, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x47, 0x72, 0x61,
	0x70, 0x68, 0x54, 0x79, 0x70, 0x65, 0x42, 0x05, 0xaa, 0x01, 0x02, 0x08, 0x01, 0x52, 0x09, 0x67,
	0x72, 0x61, 0x70, 0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3e, 0x0a, 0x0c, 0x67, 0x72, 0x61, 0x70,
	0x68, 0x5f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x61, 0x73, 0x74, 0x2e, 0x47, 0x72, 0x61, 0x70, 0x68, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x42, 0x05, 0xaa, 0x01, 0x02, 0x08, 0x01, 0x52, 0x0b, 0x67, 0x72, 0x61,
	0x70, 0x68, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x74, 0x0a, 0x12, 0x44, 0x72, 0x6f, 0x70,
	0x47, 0x72, 0x61, 0x70, 0x68, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x69, 0x66, 0x5f, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x69, 0x66, 0x45, 0x78, 0x69, 0x73, 0x74, 0x73, 0x12, 0x41, 0x0a, 0x0f, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x6e, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x43, 0x61, 0x74, 0x61, 0x6c,
	0x6f, 0x67, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x52,
	0x0d, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x10,
	0x5a, 0x04, 0x2f, 0x61, 0x73, 0x74, 0x92, 0x03, 0x07, 0xd2, 0x3e, 0x02, 0x10, 0x03, 0x08, 0x02,
	0x62, 0x08, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x70, 0xe8, 0x07,
})

var file_catalog_modifying_statement_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_catalog_modifying_statement_proto_goTypes = []any{
	(*LinearCatalogModifyingStatement)(nil), // 0: ast.LinearCatalogModifyingStatement
	(*CatalogModifyingStatement)(nil),       // 1: ast.CatalogModifyingStatement
	(*CreateGraphStatement)(nil),            // 2: ast.CreateGraphStatement
	(*DropGraphStatement)(nil),              // 3: ast.DropGraphStatement
	(*CatalogParentAndName)(nil),            // 4: ast.CatalogParentAndName
	(*GraphType)(nil),                       // 5: ast.GraphType
	(*GraphExpression)(nil),                 // 6: ast.GraphExpression
}
var file_catalog_modifying_statement_proto_depIdxs = []int32{
	1, // 0: ast.LinearCatalogModifyingStatement.statements:type_name -> ast.CatalogModifyingStatement
	2, // 1: ast.CatalogModifyingStatement.create_graph_statement:type_name -> ast.CreateGraphStatement
	3, // 2: ast.CatalogModifyingStatement.drop_graph_statement:type_name -> ast.DropGraphStatement
	4, // 3: ast.CreateGraphStatement.parent_and_name:type_name -> ast.CatalogParentAndName
	5, // 4: ast.CreateGraphStatement.graph_type:type_name -> ast.GraphType
	6, // 5: ast.CreateGraphStatement.graph_source:type_name -> ast.GraphExpression
	4, // 6: ast.DropGraphStatement.parent_and_name:type_name -> ast.CatalogParentAndName
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_catalog_modifying_statement_proto_init() }
func file_catalog_modifying_statement_proto_init() {
	if File_catalog_modifying_statement_proto != nil {
		return
	}
	file_catalog_proto_init()
	file_graph_type_proto_init()
	file_graph_expression_proto_init()
	file_catalog_modifying_statement_proto_msgTypes[1].OneofWrappers = []any{
		(*catalogModifyingStatement_CreateGraphStatement)(nil),
		(*catalogModifyingStatement_DropGraphStatement)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_modifying_statement_proto_rawDesc), len(file_catalog_modifying_statement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_modifying_statement_proto_goTypes,
		DependencyIndexes: file_catalog_modifying_statement_proto_depIdxs,
		MessageInfos:      file_catalog_modifying_statement_proto_msgTypes,
	}.Build()
	File_catalog_modifying_statement_proto = out.File
	file_catalog_modifying_statement_proto_goTypes = nil
	file_catalog_modifying_statement_proto_depIdxs = nil
}
