// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: catalog.proto

package ast

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CatalogParentAndNameType int32

const (
	CatalogParentAndNameType_GRAPH      CatalogParentAndNameType = 0
	CatalogParentAndNameType_GRAPH_TYPE CatalogParentAndNameType = 1
)

// Enum value maps for CatalogParentAndNameType.
var (
	CatalogParentAndNameType_name = map[int32]string{
		0: "GRAPH",
		1: "GRAPH_TYPE",
	}
	CatalogParentAndNameType_value = map[string]int32{
		"GRAPH":      0,
		"GRAPH_TYPE": 1,
	}
)

func (x CatalogParentAndNameType) Enum() *CatalogParentAndNameType {
	p := new(CatalogParentAndNameType)
	*p = x
	return p
}

func (x CatalogParentAndNameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CatalogParentAndNameType) Descriptor() protoreflect.EnumDescriptor {
	return file_catalog_proto_enumTypes[0].Descriptor()
}

func (CatalogParentAndNameType) Type() protoreflect.EnumType {
	return &file_catalog_proto_enumTypes[0]
}

func (x CatalogParentAndNameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type PredefinedSchemaReference_PredefinedType int32

const (
	PredefinedSchemaReference_HOME_SCHEMA    PredefinedSchemaReference_PredefinedType = 0
	PredefinedSchemaReference_CURRENT_SCHEMA PredefinedSchemaReference_PredefinedType = 1
)

// Enum value maps for PredefinedSchemaReference_PredefinedType.
var (
	PredefinedSchemaReference_PredefinedType_name = map[int32]string{
		0: "HOME_SCHEMA",
		1: "CURRENT_SCHEMA",
	}
	PredefinedSchemaReference_PredefinedType_value = map[string]int32{
		"HOME_SCHEMA":    0,
		"CURRENT_SCHEMA": 1,
	}
)

func (x PredefinedSchemaReference_PredefinedType) Enum() *PredefinedSchemaReference_PredefinedType {
	p := new(PredefinedSchemaReference_PredefinedType)
	*p = x
	return p
}

func (x PredefinedSchemaReference_PredefinedType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PredefinedSchemaReference_PredefinedType) Descriptor() protoreflect.EnumDescriptor {
	return file_catalog_proto_enumTypes[1].Descriptor()
}

func (PredefinedSchemaReference_PredefinedType) Type() protoreflect.EnumType {
	return &file_catalog_proto_enumTypes[1]
}

func (x PredefinedSchemaReference_PredefinedType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type CatalogParentAndName struct {
	state             protoimpl.MessageState        `protogen:"opaque.v1"`
	xxx_hidden_Type   CatalogParentAndNameType      `protobuf:"varint,1,opt,name=type,enum=ast.CatalogParentAndNameType"`
	xxx_hidden_Parent *CatalogObjectParentReference `protobuf:"bytes,2,opt,name=parent"`
	xxx_hidden_Name   *Identifier                   `protobuf:"bytes,3,opt,name=name"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CatalogParentAndName) Reset() {
	*x = CatalogParentAndName{}
	mi := &file_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogParentAndName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogParentAndName) ProtoMessage() {}

func (x *CatalogParentAndName) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CatalogParentAndName) GetType() CatalogParentAndNameType {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return CatalogParentAndNameType_GRAPH
}

func (x *CatalogParentAndName) GetParent() *CatalogObjectParentReference {
	if x != nil {
		return x.xxx_hidden_Parent
	}
	return nil
}

func (x *CatalogParentAndName) GetName() *Identifier {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return nil
}

func (x *CatalogParentAndName) SetType(v CatalogParentAndNameType) {
	x.xxx_hidden_Type = v
}

func (x *CatalogParentAndName) SetParent(v *CatalogObjectParentReference) {
	x.xxx_hidden_Parent = v
}

func (x *CatalogParentAndName) SetName(v *Identifier) {
	x.xxx_hidden_Name = v
}

func (x *CatalogParentAndName) HasParent() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Parent != nil
}

func (x *CatalogParentAndName) HasName() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Name != nil
}

func (x *CatalogParentAndName) ClearParent() {
	x.xxx_hidden_Parent = nil
}

func (x *CatalogParentAndName) ClearName() {
	x.xxx_hidden_Name = nil
}

type CatalogParentAndName_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Type   CatalogParentAndNameType
	Parent *CatalogObjectParentReference
	Name   *Identifier
}

func (b0 CatalogParentAndName_builder) Build() *CatalogParentAndName {
	m0 := &CatalogParentAndName{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Parent = b.Parent
	x.xxx_hidden_Name = b.Name
	return m0
}

type CatalogObjectParentReference struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SchemaReference *SchemaReference       `protobuf:"bytes,1,opt,name=schemaReference"`
	xxx_hidden_ObjectName      *[]*Identifier         `protobuf:"bytes,2,rep,name=object_name,json=objectName"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *CatalogObjectParentReference) Reset() {
	*x = CatalogObjectParentReference{}
	mi := &file_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogObjectParentReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogObjectParentReference) ProtoMessage() {}

func (x *CatalogObjectParentReference) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CatalogObjectParentReference) GetSchemaReference() *SchemaReference {
	if x != nil {
		return x.xxx_hidden_SchemaReference
	}
	return nil
}

func (x *CatalogObjectParentReference) GetObjectName() []*Identifier {
	if x != nil {
		if x.xxx_hidden_ObjectName != nil {
			return *x.xxx_hidden_ObjectName
		}
	}
	return nil
}

func (x *CatalogObjectParentReference) SetSchemaReference(v *SchemaReference) {
	x.xxx_hidden_SchemaReference = v
}

func (x *CatalogObjectParentReference) SetObjectName(v []*Identifier) {
	x.xxx_hidden_ObjectName = &v
}

func (x *CatalogObjectParentReference) HasSchemaReference() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SchemaReference != nil
}

func (x *CatalogObjectParentReference) ClearSchemaReference() {
	x.xxx_hidden_SchemaReference = nil
}

type CatalogObjectParentReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SchemaReference *SchemaReference
	ObjectName      []*Identifier
}

func (b0 CatalogObjectParentReference_builder) Build() *CatalogObjectParentReference {
	m0 := &CatalogObjectParentReference{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SchemaReference = b.SchemaReference
	x.xxx_hidden_ObjectName = &b.ObjectName
	return m0
}

type SchemaReference struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type isSchemaReference_Type `protobuf_oneof:"type"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SchemaReference) Reset() {
	*x = SchemaReference{}
	mi := &file_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaReference) ProtoMessage() {}

func (x *SchemaReference) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SchemaReference) GetAbsoluteSchemaReference() *AbsoluteCatalogSchemaReference {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*schemaReference_AbsoluteSchemaReference); ok {
			return x.AbsoluteSchemaReference
		}
	}
	return nil
}

func (x *SchemaReference) GetRelativeSchemaReference() *RelativeCatalogSchemaReference {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*schemaReference_RelativeSchemaReference); ok {
			return x.RelativeSchemaReference
		}
	}
	return nil
}

func (x *SchemaReference) GetReferenceParameterSpecification() *ReferenceParameterSpecification {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*schemaReference_ReferenceParameterSpecification); ok {
			return x.ReferenceParameterSpecification
		}
	}
	return nil
}

func (x *SchemaReference) SetAbsoluteSchemaReference(v *AbsoluteCatalogSchemaReference) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &schemaReference_AbsoluteSchemaReference{v}
}

func (x *SchemaReference) SetRelativeSchemaReference(v *RelativeCatalogSchemaReference) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &schemaReference_RelativeSchemaReference{v}
}

func (x *SchemaReference) SetReferenceParameterSpecification(v *ReferenceParameterSpecification) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &schemaReference_ReferenceParameterSpecification{v}
}

func (x *SchemaReference) HasType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Type != nil
}

func (x *SchemaReference) HasAbsoluteSchemaReference() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*schemaReference_AbsoluteSchemaReference)
	return ok
}

func (x *SchemaReference) HasRelativeSchemaReference() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*schemaReference_RelativeSchemaReference)
	return ok
}

func (x *SchemaReference) HasReferenceParameterSpecification() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*schemaReference_ReferenceParameterSpecification)
	return ok
}

func (x *SchemaReference) ClearType() {
	x.xxx_hidden_Type = nil
}

func (x *SchemaReference) ClearAbsoluteSchemaReference() {
	if _, ok := x.xxx_hidden_Type.(*schemaReference_AbsoluteSchemaReference); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *SchemaReference) ClearRelativeSchemaReference() {
	if _, ok := x.xxx_hidden_Type.(*schemaReference_RelativeSchemaReference); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *SchemaReference) ClearReferenceParameterSpecification() {
	if _, ok := x.xxx_hidden_Type.(*schemaReference_ReferenceParameterSpecification); ok {
		x.xxx_hidden_Type = nil
	}
}

const SchemaReference_Type_not_set_case case_SchemaReference_Type = 0
const SchemaReference_AbsoluteSchemaReference_case case_SchemaReference_Type = 1
const SchemaReference_RelativeSchemaReference_case case_SchemaReference_Type = 2
const SchemaReference_ReferenceParameterSpecification_case case_SchemaReference_Type = 3

func (x *SchemaReference) WhichType() case_SchemaReference_Type {
	if x == nil {
		return SchemaReference_Type_not_set_case
	}
	switch x.xxx_hidden_Type.(type) {
	case *schemaReference_AbsoluteSchemaReference:
		return SchemaReference_AbsoluteSchemaReference_case
	case *schemaReference_RelativeSchemaReference:
		return SchemaReference_RelativeSchemaReference_case
	case *schemaReference_ReferenceParameterSpecification:
		return SchemaReference_ReferenceParameterSpecification_case
	default:
		return SchemaReference_Type_not_set_case
	}
}

type SchemaReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Type:
	AbsoluteSchemaReference         *AbsoluteCatalogSchemaReference
	RelativeSchemaReference         *RelativeCatalogSchemaReference
	ReferenceParameterSpecification *ReferenceParameterSpecification
	// -- end of xxx_hidden_Type
}

func (b0 SchemaReference_builder) Build() *SchemaReference {
	m0 := &SchemaReference{}
	b, x := &b0, m0
	_, _ = b, x
	if b.AbsoluteSchemaReference != nil {
		x.xxx_hidden_Type = &schemaReference_AbsoluteSchemaReference{b.AbsoluteSchemaReference}
	}
	if b.RelativeSchemaReference != nil {
		x.xxx_hidden_Type = &schemaReference_RelativeSchemaReference{b.RelativeSchemaReference}
	}
	if b.ReferenceParameterSpecification != nil {
		x.xxx_hidden_Type = &schemaReference_ReferenceParameterSpecification{b.ReferenceParameterSpecification}
	}
	return m0
}

type case_SchemaReference_Type protoreflect.FieldNumber

func (x case_SchemaReference_Type) String() string {
	md := file_catalog_proto_msgTypes[2].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isSchemaReference_Type interface {
	isSchemaReference_Type()
}

type schemaReference_AbsoluteSchemaReference struct {
	AbsoluteSchemaReference *AbsoluteCatalogSchemaReference `protobuf:"bytes,1,opt,name=absolute_schema_reference,json=absoluteSchemaReference,oneof"`
}

type schemaReference_RelativeSchemaReference struct {
	RelativeSchemaReference *RelativeCatalogSchemaReference `protobuf:"bytes,2,opt,name=relative_schema_reference,json=relativeSchemaReference,oneof"`
}

type schemaReference_ReferenceParameterSpecification struct {
	ReferenceParameterSpecification *ReferenceParameterSpecification `protobuf:"bytes,3,opt,name=reference_parameter_specification,json=referenceParameterSpecification,oneof"`
}

func (*schemaReference_AbsoluteSchemaReference) isSchemaReference_Type() {}

func (*schemaReference_RelativeSchemaReference) isSchemaReference_Type() {}

func (*schemaReference_ReferenceParameterSpecification) isSchemaReference_Type() {}

type AbsoluteCatalogSchemaReference struct {
	state           protoimpl.MessageState                `protogen:"opaque.v1"`
	xxx_hidden_Type isAbsoluteCatalogSchemaReference_Type `protobuf_oneof:"type"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AbsoluteCatalogSchemaReference) Reset() {
	*x = AbsoluteCatalogSchemaReference{}
	mi := &file_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsoluteCatalogSchemaReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsoluteCatalogSchemaReference) ProtoMessage() {}

func (x *AbsoluteCatalogSchemaReference) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AbsoluteCatalogSchemaReference) GetRootSchema() *RootSchema {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*absoluteCatalogSchemaReference_RootSchema); ok {
			return x.RootSchema
		}
	}
	return nil
}

func (x *AbsoluteCatalogSchemaReference) GetParentAndName() *CatalogSchemaParentAndName {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*absoluteCatalogSchemaReference_ParentAndName); ok {
			return x.ParentAndName
		}
	}
	return nil
}

func (x *AbsoluteCatalogSchemaReference) SetRootSchema(v *RootSchema) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &absoluteCatalogSchemaReference_RootSchema{v}
}

func (x *AbsoluteCatalogSchemaReference) SetParentAndName(v *CatalogSchemaParentAndName) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &absoluteCatalogSchemaReference_ParentAndName{v}
}

func (x *AbsoluteCatalogSchemaReference) HasType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Type != nil
}

func (x *AbsoluteCatalogSchemaReference) HasRootSchema() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*absoluteCatalogSchemaReference_RootSchema)
	return ok
}

func (x *AbsoluteCatalogSchemaReference) HasParentAndName() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*absoluteCatalogSchemaReference_ParentAndName)
	return ok
}

func (x *AbsoluteCatalogSchemaReference) ClearType() {
	x.xxx_hidden_Type = nil
}

func (x *AbsoluteCatalogSchemaReference) ClearRootSchema() {
	if _, ok := x.xxx_hidden_Type.(*absoluteCatalogSchemaReference_RootSchema); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *AbsoluteCatalogSchemaReference) ClearParentAndName() {
	if _, ok := x.xxx_hidden_Type.(*absoluteCatalogSchemaReference_ParentAndName); ok {
		x.xxx_hidden_Type = nil
	}
}

const AbsoluteCatalogSchemaReference_Type_not_set_case case_AbsoluteCatalogSchemaReference_Type = 0
const AbsoluteCatalogSchemaReference_RootSchema_case case_AbsoluteCatalogSchemaReference_Type = 1
const AbsoluteCatalogSchemaReference_ParentAndName_case case_AbsoluteCatalogSchemaReference_Type = 2

func (x *AbsoluteCatalogSchemaReference) WhichType() case_AbsoluteCatalogSchemaReference_Type {
	if x == nil {
		return AbsoluteCatalogSchemaReference_Type_not_set_case
	}
	switch x.xxx_hidden_Type.(type) {
	case *absoluteCatalogSchemaReference_RootSchema:
		return AbsoluteCatalogSchemaReference_RootSchema_case
	case *absoluteCatalogSchemaReference_ParentAndName:
		return AbsoluteCatalogSchemaReference_ParentAndName_case
	default:
		return AbsoluteCatalogSchemaReference_Type_not_set_case
	}
}

type AbsoluteCatalogSchemaReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Type:
	RootSchema    *RootSchema
	ParentAndName *CatalogSchemaParentAndName
	// -- end of xxx_hidden_Type
}

func (b0 AbsoluteCatalogSchemaReference_builder) Build() *AbsoluteCatalogSchemaReference {
	m0 := &AbsoluteCatalogSchemaReference{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RootSchema != nil {
		x.xxx_hidden_Type = &absoluteCatalogSchemaReference_RootSchema{b.RootSchema}
	}
	if b.ParentAndName != nil {
		x.xxx_hidden_Type = &absoluteCatalogSchemaReference_ParentAndName{b.ParentAndName}
	}
	return m0
}

type case_AbsoluteCatalogSchemaReference_Type protoreflect.FieldNumber

func (x case_AbsoluteCatalogSchemaReference_Type) String() string {
	md := file_catalog_proto_msgTypes[3].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isAbsoluteCatalogSchemaReference_Type interface {
	isAbsoluteCatalogSchemaReference_Type()
}

type absoluteCatalogSchemaReference_RootSchema struct {
	RootSchema *RootSchema `protobuf:"bytes,1,opt,name=root_schema,json=rootSchema,oneof"`
}

type absoluteCatalogSchemaReference_ParentAndName struct {
	ParentAndName *CatalogSchemaParentAndName `protobuf:"bytes,2,opt,name=parent_and_name,json=parentAndName,oneof"`
}

func (*absoluteCatalogSchemaReference_RootSchema) isAbsoluteCatalogSchemaReference_Type() {}

func (*absoluteCatalogSchemaReference_ParentAndName) isAbsoluteCatalogSchemaReference_Type() {}

type RootSchema struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootSchema) Reset() {
	*x = RootSchema{}
	mi := &file_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootSchema) ProtoMessage() {}

func (x *RootSchema) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type RootSchema_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 RootSchema_builder) Build() *RootSchema {
	m0 := &RootSchema{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type CatalogSchemaParentAndName struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DirectoryPath *DirectoryPath         `protobuf:"bytes,1,opt,name=directory_path,json=directoryPath"`
	xxx_hidden_SchemaName    *Identifier            `protobuf:"bytes,2,opt,name=schema_name,json=schemaName"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CatalogSchemaParentAndName) Reset() {
	*x = CatalogSchemaParentAndName{}
	mi := &file_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CatalogSchemaParentAndName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatalogSchemaParentAndName) ProtoMessage() {}

func (x *CatalogSchemaParentAndName) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CatalogSchemaParentAndName) GetDirectoryPath() *DirectoryPath {
	if x != nil {
		return x.xxx_hidden_DirectoryPath
	}
	return nil
}

func (x *CatalogSchemaParentAndName) GetSchemaName() *Identifier {
	if x != nil {
		return x.xxx_hidden_SchemaName
	}
	return nil
}

func (x *CatalogSchemaParentAndName) SetDirectoryPath(v *DirectoryPath) {
	x.xxx_hidden_DirectoryPath = v
}

func (x *CatalogSchemaParentAndName) SetSchemaName(v *Identifier) {
	x.xxx_hidden_SchemaName = v
}

func (x *CatalogSchemaParentAndName) HasDirectoryPath() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DirectoryPath != nil
}

func (x *CatalogSchemaParentAndName) HasSchemaName() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SchemaName != nil
}

func (x *CatalogSchemaParentAndName) ClearDirectoryPath() {
	x.xxx_hidden_DirectoryPath = nil
}

func (x *CatalogSchemaParentAndName) ClearSchemaName() {
	x.xxx_hidden_SchemaName = nil
}

type CatalogSchemaParentAndName_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	DirectoryPath *DirectoryPath
	SchemaName    *Identifier
}

func (b0 CatalogSchemaParentAndName_builder) Build() *CatalogSchemaParentAndName {
	m0 := &CatalogSchemaParentAndName{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_DirectoryPath = b.DirectoryPath
	x.xxx_hidden_SchemaName = b.SchemaName
	return m0
}

type RelativeCatalogSchemaReference struct {
	state           protoimpl.MessageState                `protogen:"opaque.v1"`
	xxx_hidden_Type isRelativeCatalogSchemaReference_Type `protobuf_oneof:"type"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RelativeCatalogSchemaReference) Reset() {
	*x = RelativeCatalogSchemaReference{}
	mi := &file_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelativeCatalogSchemaReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelativeCatalogSchemaReference) ProtoMessage() {}

func (x *RelativeCatalogSchemaReference) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RelativeCatalogSchemaReference) GetPredefinedSchema() *PredefinedSchemaReference {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*relativeCatalogSchemaReference_PredefinedSchema); ok {
			return x.PredefinedSchema
		}
	}
	return nil
}

func (x *RelativeCatalogSchemaReference) GetParentAndName() *CatalogSchemaParentAndName {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*relativeCatalogSchemaReference_ParentAndName); ok {
			return x.ParentAndName
		}
	}
	return nil
}

func (x *RelativeCatalogSchemaReference) SetPredefinedSchema(v *PredefinedSchemaReference) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &relativeCatalogSchemaReference_PredefinedSchema{v}
}

func (x *RelativeCatalogSchemaReference) SetParentAndName(v *CatalogSchemaParentAndName) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &relativeCatalogSchemaReference_ParentAndName{v}
}

func (x *RelativeCatalogSchemaReference) HasType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Type != nil
}

func (x *RelativeCatalogSchemaReference) HasPredefinedSchema() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*relativeCatalogSchemaReference_PredefinedSchema)
	return ok
}

func (x *RelativeCatalogSchemaReference) HasParentAndName() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*relativeCatalogSchemaReference_ParentAndName)
	return ok
}

func (x *RelativeCatalogSchemaReference) ClearType() {
	x.xxx_hidden_Type = nil
}

func (x *RelativeCatalogSchemaReference) ClearPredefinedSchema() {
	if _, ok := x.xxx_hidden_Type.(*relativeCatalogSchemaReference_PredefinedSchema); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *RelativeCatalogSchemaReference) ClearParentAndName() {
	if _, ok := x.xxx_hidden_Type.(*relativeCatalogSchemaReference_ParentAndName); ok {
		x.xxx_hidden_Type = nil
	}
}

const RelativeCatalogSchemaReference_Type_not_set_case case_RelativeCatalogSchemaReference_Type = 0
const RelativeCatalogSchemaReference_PredefinedSchema_case case_RelativeCatalogSchemaReference_Type = 1
const RelativeCatalogSchemaReference_ParentAndName_case case_RelativeCatalogSchemaReference_Type = 2

func (x *RelativeCatalogSchemaReference) WhichType() case_RelativeCatalogSchemaReference_Type {
	if x == nil {
		return RelativeCatalogSchemaReference_Type_not_set_case
	}
	switch x.xxx_hidden_Type.(type) {
	case *relativeCatalogSchemaReference_PredefinedSchema:
		return RelativeCatalogSchemaReference_PredefinedSchema_case
	case *relativeCatalogSchemaReference_ParentAndName:
		return RelativeCatalogSchemaReference_ParentAndName_case
	default:
		return RelativeCatalogSchemaReference_Type_not_set_case
	}
}

type RelativeCatalogSchemaReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Type:
	PredefinedSchema *PredefinedSchemaReference
	ParentAndName    *CatalogSchemaParentAndName
	// -- end of xxx_hidden_Type
}

func (b0 RelativeCatalogSchemaReference_builder) Build() *RelativeCatalogSchemaReference {
	m0 := &RelativeCatalogSchemaReference{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PredefinedSchema != nil {
		x.xxx_hidden_Type = &relativeCatalogSchemaReference_PredefinedSchema{b.PredefinedSchema}
	}
	if b.ParentAndName != nil {
		x.xxx_hidden_Type = &relativeCatalogSchemaReference_ParentAndName{b.ParentAndName}
	}
	return m0
}

type case_RelativeCatalogSchemaReference_Type protoreflect.FieldNumber

func (x case_RelativeCatalogSchemaReference_Type) String() string {
	md := file_catalog_proto_msgTypes[6].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isRelativeCatalogSchemaReference_Type interface {
	isRelativeCatalogSchemaReference_Type()
}

type relativeCatalogSchemaReference_PredefinedSchema struct {
	PredefinedSchema *PredefinedSchemaReference `protobuf:"bytes,1,opt,name=predefined_schema,json=predefinedSchema,oneof"`
}

type relativeCatalogSchemaReference_ParentAndName struct {
	ParentAndName *CatalogSchemaParentAndName `protobuf:"bytes,2,opt,name=parent_and_name,json=parentAndName,oneof"`
}

func (*relativeCatalogSchemaReference_PredefinedSchema) isRelativeCatalogSchemaReference_Type() {}

func (*relativeCatalogSchemaReference_ParentAndName) isRelativeCatalogSchemaReference_Type() {}

type PredefinedSchemaReference struct {
	state            protoimpl.MessageState                   `protogen:"opaque.v1"`
	xxx_hidden_Value PredefinedSchemaReference_PredefinedType `protobuf:"varint,1,opt,name=value,enum=ast.PredefinedSchemaReference_PredefinedType"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PredefinedSchemaReference) Reset() {
	*x = PredefinedSchemaReference{}
	mi := &file_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredefinedSchemaReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredefinedSchemaReference) ProtoMessage() {}

func (x *PredefinedSchemaReference) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PredefinedSchemaReference) GetValue() PredefinedSchemaReference_PredefinedType {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return PredefinedSchemaReference_HOME_SCHEMA
}

func (x *PredefinedSchemaReference) SetValue(v PredefinedSchemaReference_PredefinedType) {
	x.xxx_hidden_Value = v
}

type PredefinedSchemaReference_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value PredefinedSchemaReference_PredefinedType
}

func (b0 PredefinedSchemaReference_builder) Build() *PredefinedSchemaReference {
	m0 := &PredefinedSchemaReference{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Value = b.Value
	return m0
}

type DirectoryPath struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value string                 `protobuf:"bytes,1,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DirectoryPath) Reset() {
	*x = DirectoryPath{}
	mi := &file_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectoryPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectoryPath) ProtoMessage() {}

func (x *DirectoryPath) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DirectoryPath) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *DirectoryPath) SetValue(v string) {
	x.xxx_hidden_Value = v
}

type DirectoryPath_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Value string
}

func (b0 DirectoryPath_builder) Build() *DirectoryPath {
	m0 := &DirectoryPath{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Value = b.Value
	return m0
}

var File_catalog_proto protoreflect.FileDescriptor

var file_catalog_proto_rawDesc = string([]byte{
	0x0a, 0x0d, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x61, 0x73, 0x74, 0x1a, 0x21, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x5f, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x6c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x6c,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb0, 0x01, 0x0a, 0x14, 0x43, 0x61, 0x74, 0x61,
	0x6c, 0x6f, 0x67, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x31, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d,
	0x2e, 0x61, 0x73, 0x74, 0x2e, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x50, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x41, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x40, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f,
	0x67, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x42, 0x05, 0xaa, 0x01, 0x02, 0x08, 0x01, 0x52, 0x06, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x97, 0x01, 0x0a, 0x1c, 0x43,
	0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x50, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x0f, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x42, 0x05, 0xaa, 0x01, 0x02, 0x08,
	0x01, 0x52, 0x0f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x12, 0x30, 0x0a, 0x0b, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0xd3, 0x02, 0x0a, 0x0f, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x61, 0x0a, 0x19, 0x61, 0x62, 0x73, 0x6f,
	0x6c, 0x75, 0x74, 0x65, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x5f, 0x72, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61, 0x73,
	0x74, 0x2e, 0x41, 0x62, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x65, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f,
	0x67, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x48, 0x00, 0x52, 0x17, 0x61, 0x62, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x65, 0x53, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x61, 0x0a, 0x19, 0x72,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x5f, 0x72,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x61, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x43, 0x61, 0x74,
	0x61, 0x6c, 0x6f, 0x67, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x48, 0x00, 0x52, 0x17, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x53,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x72,
	0x0a, 0x21, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x5f, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x61, 0x73, 0x74, 0x2e,
	0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48,
	0x00, 0x52, 0x1f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xa7, 0x01, 0x0a, 0x1e, 0x41,
	0x62, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x65, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x53, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x32, 0x0a,
	0x0b, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x74, 0x53, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x48, 0x00, 0x52, 0x0a, 0x72, 0x6f, 0x6f, 0x74, 0x53, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x12, 0x49, 0x0a, 0x0f, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x6e, 0x64, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x73, 0x74,
	0x2e, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x50, 0x61,
	0x72, 0x65, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x06, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x22, 0x0c, 0x0a, 0x0a, 0x52, 0x6f, 0x6f, 0x74, 0x53, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x22, 0x89, 0x01, 0x0a, 0x1a, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x53, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x39, 0x0a, 0x0e, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x73, 0x74, 0x2e,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x50, 0x61, 0x74, 0x68, 0x52, 0x0d, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x50, 0x61, 0x74, 0x68, 0x12, 0x30, 0x0a, 0x0b,
	0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x52, 0x0a, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xc2,
	0x01, 0x0a, 0x1e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x76, 0x65, 0x43, 0x61, 0x74, 0x61, 0x6c,
	0x6f, 0x67, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x12, 0x4d, 0x0a, 0x11, 0x70, 0x72, 0x65, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x5f,
	0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61,
	0x73, 0x74, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x53, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x48, 0x00, 0x52, 0x10,
	0x70, 0x72, 0x65, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x12, 0x49, 0x0a, 0x0f, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x6e, 0x64, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x73, 0x74, 0x2e,
	0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x50, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x70, 0x61,
	0x72, 0x65, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x22, 0x97, 0x01, 0x0a, 0x19, 0x50, 0x72, 0x65, 0x64, 0x65, 0x66, 0x69, 0x6e,
	0x65, 0x64, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x12, 0x43, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x2d, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x50, 0x72, 0x65, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65,
	0x64, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x2e, 0x50, 0x72, 0x65, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x35, 0x0a, 0x0e, 0x50, 0x72, 0x65, 0x64, 0x65, 0x66,
	0x69, 0x6e, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x48, 0x4f, 0x4d, 0x45,
	0x5f, 0x53, 0x43, 0x48, 0x45, 0x4d, 0x41, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x55, 0x52,
	0x52, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x43, 0x48, 0x45, 0x4d, 0x41, 0x10, 0x01, 0x22, 0x25, 0x0a,
	0x0d, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x50, 0x61, 0x74, 0x68, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x2a, 0x35, 0x0a, 0x18, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x50,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x09, 0x0a, 0x05, 0x47, 0x52, 0x41, 0x50, 0x48, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x47,
	0x52, 0x41, 0x50, 0x48, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x10, 0x01, 0x42, 0x10, 0x5a, 0x04, 0x2f,
	0x61, 0x73, 0x74, 0x92, 0x03, 0x07, 0xd2, 0x3e, 0x02, 0x10, 0x03, 0x08, 0x02, 0x62, 0x08, 0x65,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x70, 0xe8, 0x07,
})

var file_catalog_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_catalog_proto_goTypes = []any{
	(CatalogParentAndNameType)(0),                 // 0: ast.CatalogParentAndNameType
	(PredefinedSchemaReference_PredefinedType)(0), // 1: ast.PredefinedSchemaReference.PredefinedType
	(*CatalogParentAndName)(nil),                  // 2: ast.CatalogParentAndName
	(*CatalogObjectParentReference)(nil),          // 3: ast.CatalogObjectParentReference
	(*SchemaReference)(nil),                       // 4: ast.SchemaReference
	(*AbsoluteCatalogSchemaReference)(nil),        // 5: ast.AbsoluteCatalogSchemaReference
	(*RootSchema)(nil),                            // 6: ast.RootSchema
	(*CatalogSchemaParentAndName)(nil),            // 7: ast.CatalogSchemaParentAndName
	(*RelativeCatalogSchemaReference)(nil),        // 8: ast.RelativeCatalogSchemaReference
	(*PredefinedSchemaReference)(nil),             // 9: ast.PredefinedSchemaReference
	(*DirectoryPath)(nil),                         // 10: ast.DirectoryPath
	(*Identifier)(nil),                            // 11: ast.Identifier
	(*ReferenceParameterSpecification)(nil),       // 12: ast.ReferenceParameterSpecification
}
var file_catalog_proto_depIdxs = []int32{
	0,  // 0: ast.CatalogParentAndName.type:type_name -> ast.CatalogParentAndNameType
	3,  // 1: ast.CatalogParentAndName.parent:type_name -> ast.CatalogObjectParentReference
	11, // 2: ast.CatalogParentAndName.name:type_name -> ast.Identifier
	4,  // 3: ast.CatalogObjectParentReference.schemaReference:type_name -> ast.SchemaReference
	11, // 4: ast.CatalogObjectParentReference.object_name:type_name -> ast.Identifier
	5,  // 5: ast.SchemaReference.absolute_schema_reference:type_name -> ast.AbsoluteCatalogSchemaReference
	8,  // 6: ast.SchemaReference.relative_schema_reference:type_name -> ast.RelativeCatalogSchemaReference
	12, // 7: ast.SchemaReference.reference_parameter_specification:type_name -> ast.ReferenceParameterSpecification
	6,  // 8: ast.AbsoluteCatalogSchemaReference.root_schema:type_name -> ast.RootSchema
	7,  // 9: ast.AbsoluteCatalogSchemaReference.parent_and_name:type_name -> ast.CatalogSchemaParentAndName
	10, // 10: ast.CatalogSchemaParentAndName.directory_path:type_name -> ast.DirectoryPath
	11, // 11: ast.CatalogSchemaParentAndName.schema_name:type_name -> ast.Identifier
	9,  // 12: ast.RelativeCatalogSchemaReference.predefined_schema:type_name -> ast.PredefinedSchemaReference
	7,  // 13: ast.RelativeCatalogSchemaReference.parent_and_name:type_name -> ast.CatalogSchemaParentAndName
	1,  // 14: ast.PredefinedSchemaReference.value:type_name -> ast.PredefinedSchemaReference.PredefinedType
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_catalog_proto_init() }
func file_catalog_proto_init() {
	if File_catalog_proto != nil {
		return
	}
	file_literals_proto_init()
	file_catalog_proto_msgTypes[2].OneofWrappers = []any{
		(*schemaReference_AbsoluteSchemaReference)(nil),
		(*schemaReference_RelativeSchemaReference)(nil),
		(*schemaReference_ReferenceParameterSpecification)(nil),
	}
	file_catalog_proto_msgTypes[3].OneofWrappers = []any{
		(*absoluteCatalogSchemaReference_RootSchema)(nil),
		(*absoluteCatalogSchemaReference_ParentAndName)(nil),
	}
	file_catalog_proto_msgTypes[6].OneofWrappers = []any{
		(*relativeCatalogSchemaReference_PredefinedSchema)(nil),
		(*relativeCatalogSchemaReference_ParentAndName)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_proto_rawDesc), len(file_catalog_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_proto_depIdxs,
		EnumInfos:         file_catalog_proto_enumTypes,
		MessageInfos:      file_catalog_proto_msgTypes,
	}.Build()
	File_catalog_proto = out.File
	file_catalog_proto_goTypes = nil
	file_catalog_proto_depIdxs = nil
}
