// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: procedure_body.proto

package ast

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcedureBody struct {
	state                                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AtSchemaClause                 *SchemaReference       `protobuf:"bytes,1,opt,name=at_schema_clause,json=atSchemaClause"`
	xxx_hidden_BindingVariableDefinitionBlock *BindingVariableDef    `protobuf:"bytes,2,opt,name=binding_variable_definition_block,json=bindingVariableDefinitionBlock"`
	xxx_hidden_StatementBlock                 *StatementBlock        `protobuf:"bytes,3,opt,name=statement_block,json=statementBlock"`
	unknownFields                             protoimpl.UnknownFields
	sizeCache                                 protoimpl.SizeCache
}

func (x *ProcedureBody) Reset() {
	*x = ProcedureBody{}
	mi := &file_procedure_body_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcedureBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcedureBody) ProtoMessage() {}

func (x *ProcedureBody) ProtoReflect() protoreflect.Message {
	mi := &file_procedure_body_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProcedureBody) GetAtSchemaClause() *SchemaReference {
	if x != nil {
		return x.xxx_hidden_AtSchemaClause
	}
	return nil
}

func (x *ProcedureBody) GetBindingVariableDefinitionBlock() *BindingVariableDef {
	if x != nil {
		return x.xxx_hidden_BindingVariableDefinitionBlock
	}
	return nil
}

func (x *ProcedureBody) GetStatementBlock() *StatementBlock {
	if x != nil {
		return x.xxx_hidden_StatementBlock
	}
	return nil
}

func (x *ProcedureBody) SetAtSchemaClause(v *SchemaReference) {
	x.xxx_hidden_AtSchemaClause = v
}

func (x *ProcedureBody) SetBindingVariableDefinitionBlock(v *BindingVariableDef) {
	x.xxx_hidden_BindingVariableDefinitionBlock = v
}

func (x *ProcedureBody) SetStatementBlock(v *StatementBlock) {
	x.xxx_hidden_StatementBlock = v
}

func (x *ProcedureBody) HasAtSchemaClause() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AtSchemaClause != nil
}

func (x *ProcedureBody) HasBindingVariableDefinitionBlock() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_BindingVariableDefinitionBlock != nil
}

func (x *ProcedureBody) HasStatementBlock() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_StatementBlock != nil
}

func (x *ProcedureBody) ClearAtSchemaClause() {
	x.xxx_hidden_AtSchemaClause = nil
}

func (x *ProcedureBody) ClearBindingVariableDefinitionBlock() {
	x.xxx_hidden_BindingVariableDefinitionBlock = nil
}

func (x *ProcedureBody) ClearStatementBlock() {
	x.xxx_hidden_StatementBlock = nil
}

type ProcedureBody_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AtSchemaClause                 *SchemaReference
	BindingVariableDefinitionBlock *BindingVariableDef
	StatementBlock                 *StatementBlock
}

func (b0 ProcedureBody_builder) Build() *ProcedureBody {
	m0 := &ProcedureBody{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_AtSchemaClause = b.AtSchemaClause
	x.xxx_hidden_BindingVariableDefinitionBlock = b.BindingVariableDefinitionBlock
	x.xxx_hidden_StatementBlock = b.StatementBlock
	return m0
}

type BindingVariableDef struct {
	state           protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_Type isBindingVariableDef_Type `protobuf_oneof:"type"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BindingVariableDef) Reset() {
	*x = BindingVariableDef{}
	mi := &file_procedure_body_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindingVariableDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindingVariableDef) ProtoMessage() {}

func (x *BindingVariableDef) ProtoReflect() protoreflect.Message {
	mi := &file_procedure_body_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BindingVariableDef) GetGraphVariableDef() *GraphVariableDef {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*bindingVariableDef_GraphVariableDef); ok {
			return x.GraphVariableDef
		}
	}
	return nil
}

func (x *BindingVariableDef) GetBindingTableVariableDef() *BindingTableVariableDef {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*bindingVariableDef_BindingTableVariableDef); ok {
			return x.BindingTableVariableDef
		}
	}
	return nil
}

func (x *BindingVariableDef) GetValueVariableDef() *ValueVariableDef {
	if x != nil {
		if x, ok := x.xxx_hidden_Type.(*bindingVariableDef_ValueVariableDef); ok {
			return x.ValueVariableDef
		}
	}
	return nil
}

func (x *BindingVariableDef) SetGraphVariableDef(v *GraphVariableDef) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &bindingVariableDef_GraphVariableDef{v}
}

func (x *BindingVariableDef) SetBindingTableVariableDef(v *BindingTableVariableDef) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &bindingVariableDef_BindingTableVariableDef{v}
}

func (x *BindingVariableDef) SetValueVariableDef(v *ValueVariableDef) {
	if v == nil {
		x.xxx_hidden_Type = nil
		return
	}
	x.xxx_hidden_Type = &bindingVariableDef_ValueVariableDef{v}
}

func (x *BindingVariableDef) HasType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Type != nil
}

func (x *BindingVariableDef) HasGraphVariableDef() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*bindingVariableDef_GraphVariableDef)
	return ok
}

func (x *BindingVariableDef) HasBindingTableVariableDef() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*bindingVariableDef_BindingTableVariableDef)
	return ok
}

func (x *BindingVariableDef) HasValueVariableDef() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Type.(*bindingVariableDef_ValueVariableDef)
	return ok
}

func (x *BindingVariableDef) ClearType() {
	x.xxx_hidden_Type = nil
}

func (x *BindingVariableDef) ClearGraphVariableDef() {
	if _, ok := x.xxx_hidden_Type.(*bindingVariableDef_GraphVariableDef); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *BindingVariableDef) ClearBindingTableVariableDef() {
	if _, ok := x.xxx_hidden_Type.(*bindingVariableDef_BindingTableVariableDef); ok {
		x.xxx_hidden_Type = nil
	}
}

func (x *BindingVariableDef) ClearValueVariableDef() {
	if _, ok := x.xxx_hidden_Type.(*bindingVariableDef_ValueVariableDef); ok {
		x.xxx_hidden_Type = nil
	}
}

const BindingVariableDef_Type_not_set_case case_BindingVariableDef_Type = 0
const BindingVariableDef_GraphVariableDef_case case_BindingVariableDef_Type = 1
const BindingVariableDef_BindingTableVariableDef_case case_BindingVariableDef_Type = 2
const BindingVariableDef_ValueVariableDef_case case_BindingVariableDef_Type = 3

func (x *BindingVariableDef) WhichType() case_BindingVariableDef_Type {
	if x == nil {
		return BindingVariableDef_Type_not_set_case
	}
	switch x.xxx_hidden_Type.(type) {
	case *bindingVariableDef_GraphVariableDef:
		return BindingVariableDef_GraphVariableDef_case
	case *bindingVariableDef_BindingTableVariableDef:
		return BindingVariableDef_BindingTableVariableDef_case
	case *bindingVariableDef_ValueVariableDef:
		return BindingVariableDef_ValueVariableDef_case
	default:
		return BindingVariableDef_Type_not_set_case
	}
}

type BindingVariableDef_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Type:
	GraphVariableDef        *GraphVariableDef
	BindingTableVariableDef *BindingTableVariableDef
	ValueVariableDef        *ValueVariableDef
	// -- end of xxx_hidden_Type
}

func (b0 BindingVariableDef_builder) Build() *BindingVariableDef {
	m0 := &BindingVariableDef{}
	b, x := &b0, m0
	_, _ = b, x
	if b.GraphVariableDef != nil {
		x.xxx_hidden_Type = &bindingVariableDef_GraphVariableDef{b.GraphVariableDef}
	}
	if b.BindingTableVariableDef != nil {
		x.xxx_hidden_Type = &bindingVariableDef_BindingTableVariableDef{b.BindingTableVariableDef}
	}
	if b.ValueVariableDef != nil {
		x.xxx_hidden_Type = &bindingVariableDef_ValueVariableDef{b.ValueVariableDef}
	}
	return m0
}

type case_BindingVariableDef_Type protoreflect.FieldNumber

func (x case_BindingVariableDef_Type) String() string {
	md := file_procedure_body_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isBindingVariableDef_Type interface {
	isBindingVariableDef_Type()
}

type bindingVariableDef_GraphVariableDef struct {
	GraphVariableDef *GraphVariableDef `protobuf:"bytes,1,opt,name=graph_variable_def,json=graphVariableDef,oneof"`
}

type bindingVariableDef_BindingTableVariableDef struct {
	BindingTableVariableDef *BindingTableVariableDef `protobuf:"bytes,2,opt,name=binding_table_variable_def,json=bindingTableVariableDef,oneof"`
}

type bindingVariableDef_ValueVariableDef struct {
	ValueVariableDef *ValueVariableDef `protobuf:"bytes,3,opt,name=value_variable_def,json=valueVariableDef,oneof"`
}

func (*bindingVariableDef_GraphVariableDef) isBindingVariableDef_Type() {}

func (*bindingVariableDef_BindingTableVariableDef) isBindingVariableDef_Type() {}

func (*bindingVariableDef_ValueVariableDef) isBindingVariableDef_Type() {}

var File_procedure_body_proto protoreflect.FileDescriptor

var file_procedure_body_proto_rawDesc = string([]byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x64, 0x75, 0x72, 0x65, 0x5f, 0x62, 0x6f, 0x64, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x73, 0x74, 0x1a, 0x21, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x5f,
	0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x0d, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18,
	0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x64,
	0x65, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x5f, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65,
	0x5f, 0x64, 0x65, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x64, 0x65, 0x66, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xff, 0x01, 0x0a, 0x0d, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x64, 0x75,
	0x72, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x45, 0x0a, 0x10, 0x61, 0x74, 0x5f, 0x73, 0x63, 0x68,
	0x65, 0x6d, 0x61, 0x5f, 0x63, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x42, 0x05, 0xaa, 0x01, 0x02, 0x08, 0x01, 0x52, 0x0e, 0x61,
	0x74, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x12, 0x69, 0x0a,
	0x21, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c,
	0x65, 0x5f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x42,
	0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65,
	0x66, 0x42, 0x05, 0xaa, 0x01, 0x02, 0x08, 0x01, 0x52, 0x1e, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x3c, 0x0a, 0x0f, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x0e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x22, 0x87, 0x02, 0x0a, 0x12, 0x42, 0x69, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65, 0x66, 0x12, 0x45, 0x0a,
	0x12, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x5f,
	0x64, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x73, 0x74, 0x2e,
	0x47, 0x72, 0x61, 0x70, 0x68, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65, 0x66,
	0x48, 0x00, 0x52, 0x10, 0x67, 0x72, 0x61, 0x70, 0x68, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c,
	0x65, 0x44, 0x65, 0x66, 0x12, 0x5b, 0x0a, 0x1a, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x5f,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x64,
	0x65, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x42,
	0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x72, 0x69, 0x61,
	0x62, 0x6c, 0x65, 0x44, 0x65, 0x66, 0x48, 0x00, 0x52, 0x17, 0x62, 0x69, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65,
	0x66, 0x12, 0x45, 0x0a, 0x12, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61,
	0x62, 0x6c, 0x65, 0x5f, 0x64, 0x65, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x61, 0x73, 0x74, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c,
	0x65, 0x44, 0x65, 0x66, 0x48, 0x00, 0x52, 0x10, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x56, 0x61, 0x72,
	0x69, 0x61, 0x62, 0x6c, 0x65, 0x44, 0x65, 0x66, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x42, 0x10, 0x5a, 0x04, 0x2f, 0x61, 0x73, 0x74, 0x92, 0x03, 0x07, 0xd2, 0x3e, 0x02, 0x10, 0x03,
	0x08, 0x02, 0x62, 0x08, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x70, 0xe8, 0x07,
})

var file_procedure_body_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_procedure_body_proto_goTypes = []any{
	(*ProcedureBody)(nil),           // 0: ast.ProcedureBody
	(*BindingVariableDef)(nil),      // 1: ast.BindingVariableDef
	(*SchemaReference)(nil),         // 2: ast.SchemaReference
	(*StatementBlock)(nil),          // 3: ast.StatementBlock
	(*GraphVariableDef)(nil),        // 4: ast.GraphVariableDef
	(*BindingTableVariableDef)(nil), // 5: ast.BindingTableVariableDef
	(*ValueVariableDef)(nil),        // 6: ast.ValueVariableDef
}
var file_procedure_body_proto_depIdxs = []int32{
	2, // 0: ast.ProcedureBody.at_schema_clause:type_name -> ast.SchemaReference
	1, // 1: ast.ProcedureBody.binding_variable_definition_block:type_name -> ast.BindingVariableDef
	3, // 2: ast.ProcedureBody.statement_block:type_name -> ast.StatementBlock
	4, // 3: ast.BindingVariableDef.graph_variable_def:type_name -> ast.GraphVariableDef
	5, // 4: ast.BindingVariableDef.binding_table_variable_def:type_name -> ast.BindingTableVariableDef
	6, // 5: ast.BindingVariableDef.value_variable_def:type_name -> ast.ValueVariableDef
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_procedure_body_proto_init() }
func file_procedure_body_proto_init() {
	if File_procedure_body_proto != nil {
		return
	}
	file_statement_proto_init()
	file_catalog_proto_init()
	file_graph_variable_def_proto_init()
	file_binding_table_variable_def_proto_init()
	file_value_variable_def_proto_init()
	file_procedure_body_proto_msgTypes[1].OneofWrappers = []any{
		(*bindingVariableDef_GraphVariableDef)(nil),
		(*bindingVariableDef_BindingTableVariableDef)(nil),
		(*bindingVariableDef_ValueVariableDef)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_procedure_body_proto_rawDesc), len(file_procedure_body_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_procedure_body_proto_goTypes,
		DependencyIndexes: file_procedure_body_proto_depIdxs,
		MessageInfos:      file_procedure_body_proto_msgTypes,
	}.Build()
	File_procedure_body_proto = out.File
	file_procedure_body_proto_goTypes = nil
	file_procedure_body_proto_depIdxs = nil
}
