// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: transaction_commands.proto

package ast

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartTransactionCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTransactionCommand) Reset() {
	*x = StartTransactionCommand{}
	mi := &file_transaction_commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTransactionCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTransactionCommand) ProtoMessage() {}

func (x *StartTransactionCommand) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTransactionCommand.ProtoReflect.Descriptor instead.
func (*StartTransactionCommand) Descriptor() ([]byte, []int) {
	return file_transaction_commands_proto_rawDescGZIP(), []int{0}
}

type EndTransactionCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndTransactionCommand) Reset() {
	*x = EndTransactionCommand{}
	mi := &file_transaction_commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndTransactionCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndTransactionCommand) ProtoMessage() {}

func (x *EndTransactionCommand) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndTransactionCommand.ProtoReflect.Descriptor instead.
func (*EndTransactionCommand) Descriptor() ([]byte, []int) {
	return file_transaction_commands_proto_rawDescGZIP(), []int{1}
}

var File_transaction_commands_proto protoreflect.FileDescriptor

var file_transaction_commands_proto_rawDesc = string([]byte{
	0x0a, 0x1a, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x73,
	0x74, 0x22, 0x19, 0x0a, 0x17, 0x53, 0x74, 0x61, 0x72, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x17, 0x0a, 0x15,
	0x45, 0x6e, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x42, 0x06, 0x5a, 0x04, 0x2f, 0x61, 0x73, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_transaction_commands_proto_rawDescOnce sync.Once
	file_transaction_commands_proto_rawDescData []byte
)

func file_transaction_commands_proto_rawDescGZIP() []byte {
	file_transaction_commands_proto_rawDescOnce.Do(func() {
		file_transaction_commands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_commands_proto_rawDesc), len(file_transaction_commands_proto_rawDesc)))
	})
	return file_transaction_commands_proto_rawDescData
}

var file_transaction_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transaction_commands_proto_goTypes = []any{
	(*StartTransactionCommand)(nil), // 0: ast.StartTransactionCommand
	(*EndTransactionCommand)(nil),   // 1: ast.EndTransactionCommand
}
var file_transaction_commands_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transaction_commands_proto_init() }
func file_transaction_commands_proto_init() {
	if File_transaction_commands_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_commands_proto_rawDesc), len(file_transaction_commands_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transaction_commands_proto_goTypes,
		DependencyIndexes: file_transaction_commands_proto_depIdxs,
		MessageInfos:      file_transaction_commands_proto_msgTypes,
	}.Build()
	File_transaction_commands_proto = out.File
	file_transaction_commands_proto_goTypes = nil
	file_transaction_commands_proto_depIdxs = nil
}
