// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: yield_clause.proto

package ast

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type YieldClause struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_YieldItemList *[]*YieldItem          `protobuf:"bytes,1,rep,name=yield_item_list,json=yieldItemList"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *YieldClause) Reset() {
	*x = YieldClause{}
	mi := &file_yield_clause_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YieldClause) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YieldClause) ProtoMessage() {}

func (x *YieldClause) ProtoReflect() protoreflect.Message {
	mi := &file_yield_clause_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *YieldClause) GetYieldItemList() []*YieldItem {
	if x != nil {
		if x.xxx_hidden_YieldItemList != nil {
			return *x.xxx_hidden_YieldItemList
		}
	}
	return nil
}

func (x *YieldClause) SetYieldItemList(v []*YieldItem) {
	x.xxx_hidden_YieldItemList = &v
}

type YieldClause_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	YieldItemList []*YieldItem
}

func (b0 YieldClause_builder) Build() *YieldClause {
	m0 := &YieldClause{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_YieldItemList = &b.YieldItemList
	return m0
}

type YieldItem struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name  *Identifier            `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Alias *Identifier            `protobuf:"bytes,2,opt,name=alias"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *YieldItem) Reset() {
	*x = YieldItem{}
	mi := &file_yield_clause_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YieldItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YieldItem) ProtoMessage() {}

func (x *YieldItem) ProtoReflect() protoreflect.Message {
	mi := &file_yield_clause_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *YieldItem) GetName() *Identifier {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return nil
}

func (x *YieldItem) GetAlias() *Identifier {
	if x != nil {
		return x.xxx_hidden_Alias
	}
	return nil
}

func (x *YieldItem) SetName(v *Identifier) {
	x.xxx_hidden_Name = v
}

func (x *YieldItem) SetAlias(v *Identifier) {
	x.xxx_hidden_Alias = v
}

func (x *YieldItem) HasName() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Name != nil
}

func (x *YieldItem) HasAlias() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Alias != nil
}

func (x *YieldItem) ClearName() {
	x.xxx_hidden_Name = nil
}

func (x *YieldItem) ClearAlias() {
	x.xxx_hidden_Alias = nil
}

type YieldItem_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name  *Identifier
	Alias *Identifier
}

func (b0 YieldItem_builder) Build() *YieldItem {
	m0 := &YieldItem{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Alias = b.Alias
	return m0
}

var File_yield_clause_proto protoreflect.FileDescriptor

var file_yield_clause_proto_rawDesc = string([]byte{
	0x0a, 0x12, 0x79, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x63, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x73, 0x74, 0x1a, 0x21, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x67, 0x6f, 0x5f, 0x66, 0x65,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x6c, 0x69,
	0x74, 0x65, 0x72, 0x61, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a, 0x0b,
	0x59, 0x69, 0x65, 0x6c, 0x64, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0f, 0x79,
	0x69, 0x65, 0x6c, 0x64, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x59, 0x69, 0x65, 0x6c, 0x64,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x0d, 0x79, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x5e, 0x0a, 0x09, 0x59, 0x69, 0x65, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x23, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x61, 0x73, 0x74, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x05, 0x61, 0x6c, 0x69, 0x61, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x66, 0x69, 0x65, 0x72, 0x42, 0x05, 0xaa, 0x01, 0x02, 0x08, 0x01, 0x52, 0x05, 0x61, 0x6c,
	0x69, 0x61, 0x73, 0x42, 0x10, 0x5a, 0x04, 0x2f, 0x61, 0x73, 0x74, 0x92, 0x03, 0x07, 0xd2, 0x3e,
	0x02, 0x10, 0x03, 0x08, 0x02, 0x62, 0x08, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x70,
	0xe8, 0x07,
})

var file_yield_clause_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_yield_clause_proto_goTypes = []any{
	(*YieldClause)(nil), // 0: ast.YieldClause
	(*YieldItem)(nil),   // 1: ast.YieldItem
	(*Identifier)(nil),  // 2: ast.Identifier
}
var file_yield_clause_proto_depIdxs = []int32{
	1, // 0: ast.YieldClause.yield_item_list:type_name -> ast.YieldItem
	2, // 1: ast.YieldItem.name:type_name -> ast.Identifier
	2, // 2: ast.YieldItem.alias:type_name -> ast.Identifier
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_yield_clause_proto_init() }
func file_yield_clause_proto_init() {
	if File_yield_clause_proto != nil {
		return
	}
	file_literals_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_yield_clause_proto_rawDesc), len(file_yield_clause_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_yield_clause_proto_goTypes,
		DependencyIndexes: file_yield_clause_proto_depIdxs,
		MessageInfos:      file_yield_clause_proto_msgTypes,
	}.Build()
	File_yield_clause_proto = out.File
	file_yield_clause_proto_goTypes = nil
	file_yield_clause_proto_depIdxs = nil
}
