// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: graph_reference.proto

package ast

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GraphReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Which:
	//
	//	*GraphReference_ParentAndName
	//	*GraphReference_DelimitedGraphName
	//	*GraphReference_HomeGraph
	//	*GraphReference_ReferenceParameterSpecification
	Which         isGraphReference_Which `protobuf_oneof:"which"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphReference) Reset() {
	*x = GraphReference{}
	mi := &file_graph_reference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphReference) ProtoMessage() {}

func (x *GraphReference) ProtoReflect() protoreflect.Message {
	mi := &file_graph_reference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphReference.ProtoReflect.Descriptor instead.
func (*GraphReference) Descriptor() ([]byte, []int) {
	return file_graph_reference_proto_rawDescGZIP(), []int{0}
}

func (x *GraphReference) GetWhich() isGraphReference_Which {
	if x != nil {
		return x.Which
	}
	return nil
}

func (x *GraphReference) GetParentAndName() *CatalogParentAndName {
	if x != nil {
		if x, ok := x.Which.(*GraphReference_ParentAndName); ok {
			return x.ParentAndName
		}
	}
	return nil
}

func (x *GraphReference) GetDelimitedGraphName() *Identifier {
	if x != nil {
		if x, ok := x.Which.(*GraphReference_DelimitedGraphName); ok {
			return x.DelimitedGraphName
		}
	}
	return nil
}

func (x *GraphReference) GetHomeGraph() *HomeGraph {
	if x != nil {
		if x, ok := x.Which.(*GraphReference_HomeGraph); ok {
			return x.HomeGraph
		}
	}
	return nil
}

func (x *GraphReference) GetReferenceParameterSpecification() *ReferenceParameterSpecification {
	if x != nil {
		if x, ok := x.Which.(*GraphReference_ReferenceParameterSpecification); ok {
			return x.ReferenceParameterSpecification
		}
	}
	return nil
}

type isGraphReference_Which interface {
	isGraphReference_Which()
}

type GraphReference_ParentAndName struct {
	ParentAndName *CatalogParentAndName `protobuf:"bytes,1,opt,name=parent_and_name,json=parentAndName,proto3,oneof"`
}

type GraphReference_DelimitedGraphName struct {
	DelimitedGraphName *Identifier `protobuf:"bytes,2,opt,name=delimited_graph_name,json=delimitedGraphName,proto3,oneof"`
}

type GraphReference_HomeGraph struct {
	HomeGraph *HomeGraph `protobuf:"bytes,3,opt,name=home_graph,json=homeGraph,proto3,oneof"`
}

type GraphReference_ReferenceParameterSpecification struct {
	ReferenceParameterSpecification *ReferenceParameterSpecification `protobuf:"bytes,4,opt,name=reference_parameter_specification,json=referenceParameterSpecification,proto3,oneof"`
}

func (*GraphReference_ParentAndName) isGraphReference_Which() {}

func (*GraphReference_DelimitedGraphName) isGraphReference_Which() {}

func (*GraphReference_HomeGraph) isGraphReference_Which() {}

func (*GraphReference_ReferenceParameterSpecification) isGraphReference_Which() {}

type HomeGraph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HomeGraph) Reset() {
	*x = HomeGraph{}
	mi := &file_graph_reference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeGraph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeGraph) ProtoMessage() {}

func (x *HomeGraph) ProtoReflect() protoreflect.Message {
	mi := &file_graph_reference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeGraph.ProtoReflect.Descriptor instead.
func (*HomeGraph) Descriptor() ([]byte, []int) {
	return file_graph_reference_proto_rawDescGZIP(), []int{1}
}

var File_graph_reference_proto protoreflect.FileDescriptor

var file_graph_reference_proto_rawDesc = string([]byte{
	0x0a, 0x15, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x73, 0x74, 0x1a, 0x0d, 0x63, 0x61,
	0x74, 0x61, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x6c, 0x69, 0x74,
	0x65, 0x72, 0x61, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc8, 0x02, 0x0a, 0x0e,
	0x47, 0x72, 0x61, 0x70, 0x68, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x43,
	0x0a, 0x0f, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x6e, 0x64, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x43, 0x61,
	0x74, 0x61, 0x6c, 0x6f, 0x67, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x4e, 0x61,
	0x6d, 0x65, 0x48, 0x00, 0x52, 0x0d, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x41, 0x6e, 0x64, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x43, 0x0a, 0x14, 0x64, 0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x64,
	0x5f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x48, 0x00, 0x52, 0x12, 0x64, 0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x64, 0x47,
	0x72, 0x61, 0x70, 0x68, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2f, 0x0a, 0x0a, 0x68, 0x6f, 0x6d, 0x65,
	0x5f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61,
	0x73, 0x74, 0x2e, 0x48, 0x6f, 0x6d, 0x65, 0x47, 0x72, 0x61, 0x70, 0x68, 0x48, 0x00, 0x52, 0x09,
	0x68, 0x6f, 0x6d, 0x65, 0x47, 0x72, 0x61, 0x70, 0x68, 0x12, 0x72, 0x0a, 0x21, 0x72, 0x65, 0x66,
	0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x5f, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x61, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x53, 0x70, 0x65,
	0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x1f, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x07, 0x0a,
	0x05, 0x77, 0x68, 0x69, 0x63, 0x68, 0x22, 0x0b, 0x0a, 0x09, 0x48, 0x6f, 0x6d, 0x65, 0x47, 0x72,
	0x61, 0x70, 0x68, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6d, 0x62, 0x75, 0x72, 0x62, 0x69, 0x64, 0x67, 0x2f, 0x67, 0x6b, 0x69, 0x74, 0x2d,
	0x61, 0x73, 0x74, 0x2f, 0x67, 0x6f, 0x2f, 0x61, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var (
	file_graph_reference_proto_rawDescOnce sync.Once
	file_graph_reference_proto_rawDescData []byte
)

func file_graph_reference_proto_rawDescGZIP() []byte {
	file_graph_reference_proto_rawDescOnce.Do(func() {
		file_graph_reference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_reference_proto_rawDesc), len(file_graph_reference_proto_rawDesc)))
	})
	return file_graph_reference_proto_rawDescData
}

var file_graph_reference_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_graph_reference_proto_goTypes = []any{
	(*GraphReference)(nil),                  // 0: ast.GraphReference
	(*HomeGraph)(nil),                       // 1: ast.HomeGraph
	(*CatalogParentAndName)(nil),            // 2: ast.CatalogParentAndName
	(*Identifier)(nil),                      // 3: ast.Identifier
	(*ReferenceParameterSpecification)(nil), // 4: ast.ReferenceParameterSpecification
}
var file_graph_reference_proto_depIdxs = []int32{
	2, // 0: ast.GraphReference.parent_and_name:type_name -> ast.CatalogParentAndName
	3, // 1: ast.GraphReference.delimited_graph_name:type_name -> ast.Identifier
	1, // 2: ast.GraphReference.home_graph:type_name -> ast.HomeGraph
	4, // 3: ast.GraphReference.reference_parameter_specification:type_name -> ast.ReferenceParameterSpecification
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_graph_reference_proto_init() }
func file_graph_reference_proto_init() {
	if File_graph_reference_proto != nil {
		return
	}
	file_catalog_proto_init()
	file_literals_proto_init()
	file_graph_reference_proto_msgTypes[0].OneofWrappers = []any{
		(*GraphReference_ParentAndName)(nil),
		(*GraphReference_DelimitedGraphName)(nil),
		(*GraphReference_HomeGraph)(nil),
		(*GraphReference_ReferenceParameterSpecification)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_reference_proto_rawDesc), len(file_graph_reference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_graph_reference_proto_goTypes,
		DependencyIndexes: file_graph_reference_proto_depIdxs,
		MessageInfos:      file_graph_reference_proto_msgTypes,
	}.Build()
	File_graph_reference_proto = out.File
	file_graph_reference_proto_goTypes = nil
	file_graph_reference_proto_depIdxs = nil
}
