// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: catalog_statements.proto
// Protobuf Java Version: 4.29.3

package ast;

public final class CatalogStatements {
  private CatalogStatements() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      CatalogStatements.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CreateGraphStatementOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ast.CreateGraphStatement)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool if_not_exists = 1;</code>
     * @return Whether the ifNotExists field is set.
     */
    boolean hasIfNotExists();
    /**
     * <code>optional bool if_not_exists = 1;</code>
     * @return The ifNotExists.
     */
    boolean getIfNotExists();

    /**
     * <code>optional bool replace_graph = 2;</code>
     * @return Whether the replaceGraph field is set.
     */
    boolean hasReplaceGraph();
    /**
     * <code>optional bool replace_graph = 2;</code>
     * @return The replaceGraph.
     */
    boolean getReplaceGraph();

    /**
     * <code>.ast.CatalogParentAndName parent_and_name = 3;</code>
     * @return Whether the parentAndName field is set.
     */
    boolean hasParentAndName();
    /**
     * <code>.ast.CatalogParentAndName parent_and_name = 3;</code>
     * @return The parentAndName.
     */
    ast.Catalog.CatalogParentAndName getParentAndName();
    /**
     * <code>.ast.CatalogParentAndName parent_and_name = 3;</code>
     */
    ast.Catalog.CatalogParentAndNameOrBuilder getParentAndNameOrBuilder();

    /**
     * <code>optional .ast.GraphType graph_type = 4;</code>
     * @return Whether the graphType field is set.
     */
    boolean hasGraphType();
    /**
     * <code>optional .ast.GraphType graph_type = 4;</code>
     * @return The graphType.
     */
    ast.GraphTypeOuterClass.GraphType getGraphType();
    /**
     * <code>optional .ast.GraphType graph_type = 4;</code>
     */
    ast.GraphTypeOuterClass.GraphTypeOrBuilder getGraphTypeOrBuilder();

    /**
     * <code>optional .ast.GraphExpression graph_source = 5;</code>
     * @return Whether the graphSource field is set.
     */
    boolean hasGraphSource();
    /**
     * <code>optional .ast.GraphExpression graph_source = 5;</code>
     * @return The graphSource.
     */
    ast.GraphExpressionOuterClass.GraphExpression getGraphSource();
    /**
     * <code>optional .ast.GraphExpression graph_source = 5;</code>
     */
    ast.GraphExpressionOuterClass.GraphExpressionOrBuilder getGraphSourceOrBuilder();
  }
  /**
   * Protobuf type {@code ast.CreateGraphStatement}
   */
  public static final class CreateGraphStatement extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ast.CreateGraphStatement)
      CreateGraphStatementOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        CreateGraphStatement.class.getName());
    }
    // Use CreateGraphStatement.newBuilder() to construct.
    private CreateGraphStatement(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CreateGraphStatement() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ast.CatalogStatements.internal_static_ast_CreateGraphStatement_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ast.CatalogStatements.internal_static_ast_CreateGraphStatement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ast.CatalogStatements.CreateGraphStatement.class, ast.CatalogStatements.CreateGraphStatement.Builder.class);
    }

    private int bitField0_;
    public static final int IF_NOT_EXISTS_FIELD_NUMBER = 1;
    private boolean ifNotExists_ = false;
    /**
     * <code>optional bool if_not_exists = 1;</code>
     * @return Whether the ifNotExists field is set.
     */
    @java.lang.Override
    public boolean hasIfNotExists() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bool if_not_exists = 1;</code>
     * @return The ifNotExists.
     */
    @java.lang.Override
    public boolean getIfNotExists() {
      return ifNotExists_;
    }

    public static final int REPLACE_GRAPH_FIELD_NUMBER = 2;
    private boolean replaceGraph_ = false;
    /**
     * <code>optional bool replace_graph = 2;</code>
     * @return Whether the replaceGraph field is set.
     */
    @java.lang.Override
    public boolean hasReplaceGraph() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bool replace_graph = 2;</code>
     * @return The replaceGraph.
     */
    @java.lang.Override
    public boolean getReplaceGraph() {
      return replaceGraph_;
    }

    public static final int PARENT_AND_NAME_FIELD_NUMBER = 3;
    private ast.Catalog.CatalogParentAndName parentAndName_;
    /**
     * <code>.ast.CatalogParentAndName parent_and_name = 3;</code>
     * @return Whether the parentAndName field is set.
     */
    @java.lang.Override
    public boolean hasParentAndName() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.ast.CatalogParentAndName parent_and_name = 3;</code>
     * @return The parentAndName.
     */
    @java.lang.Override
    public ast.Catalog.CatalogParentAndName getParentAndName() {
      return parentAndName_ == null ? ast.Catalog.CatalogParentAndName.getDefaultInstance() : parentAndName_;
    }
    /**
     * <code>.ast.CatalogParentAndName parent_and_name = 3;</code>
     */
    @java.lang.Override
    public ast.Catalog.CatalogParentAndNameOrBuilder getParentAndNameOrBuilder() {
      return parentAndName_ == null ? ast.Catalog.CatalogParentAndName.getDefaultInstance() : parentAndName_;
    }

    public static final int GRAPH_TYPE_FIELD_NUMBER = 4;
    private ast.GraphTypeOuterClass.GraphType graphType_;
    /**
     * <code>optional .ast.GraphType graph_type = 4;</code>
     * @return Whether the graphType field is set.
     */
    @java.lang.Override
    public boolean hasGraphType() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .ast.GraphType graph_type = 4;</code>
     * @return The graphType.
     */
    @java.lang.Override
    public ast.GraphTypeOuterClass.GraphType getGraphType() {
      return graphType_ == null ? ast.GraphTypeOuterClass.GraphType.getDefaultInstance() : graphType_;
    }
    /**
     * <code>optional .ast.GraphType graph_type = 4;</code>
     */
    @java.lang.Override
    public ast.GraphTypeOuterClass.GraphTypeOrBuilder getGraphTypeOrBuilder() {
      return graphType_ == null ? ast.GraphTypeOuterClass.GraphType.getDefaultInstance() : graphType_;
    }

    public static final int GRAPH_SOURCE_FIELD_NUMBER = 5;
    private ast.GraphExpressionOuterClass.GraphExpression graphSource_;
    /**
     * <code>optional .ast.GraphExpression graph_source = 5;</code>
     * @return Whether the graphSource field is set.
     */
    @java.lang.Override
    public boolean hasGraphSource() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .ast.GraphExpression graph_source = 5;</code>
     * @return The graphSource.
     */
    @java.lang.Override
    public ast.GraphExpressionOuterClass.GraphExpression getGraphSource() {
      return graphSource_ == null ? ast.GraphExpressionOuterClass.GraphExpression.getDefaultInstance() : graphSource_;
    }
    /**
     * <code>optional .ast.GraphExpression graph_source = 5;</code>
     */
    @java.lang.Override
    public ast.GraphExpressionOuterClass.GraphExpressionOrBuilder getGraphSourceOrBuilder() {
      return graphSource_ == null ? ast.GraphExpressionOuterClass.GraphExpression.getDefaultInstance() : graphSource_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(1, ifNotExists_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBool(2, replaceGraph_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(3, getParentAndName());
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeMessage(4, getGraphType());
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeMessage(5, getGraphSource());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, ifNotExists_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, replaceGraph_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getParentAndName());
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getGraphType());
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getGraphSource());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ast.CatalogStatements.CreateGraphStatement)) {
        return super.equals(obj);
      }
      ast.CatalogStatements.CreateGraphStatement other = (ast.CatalogStatements.CreateGraphStatement) obj;

      if (hasIfNotExists() != other.hasIfNotExists()) return false;
      if (hasIfNotExists()) {
        if (getIfNotExists()
            != other.getIfNotExists()) return false;
      }
      if (hasReplaceGraph() != other.hasReplaceGraph()) return false;
      if (hasReplaceGraph()) {
        if (getReplaceGraph()
            != other.getReplaceGraph()) return false;
      }
      if (hasParentAndName() != other.hasParentAndName()) return false;
      if (hasParentAndName()) {
        if (!getParentAndName()
            .equals(other.getParentAndName())) return false;
      }
      if (hasGraphType() != other.hasGraphType()) return false;
      if (hasGraphType()) {
        if (!getGraphType()
            .equals(other.getGraphType())) return false;
      }
      if (hasGraphSource() != other.hasGraphSource()) return false;
      if (hasGraphSource()) {
        if (!getGraphSource()
            .equals(other.getGraphSource())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasIfNotExists()) {
        hash = (37 * hash) + IF_NOT_EXISTS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIfNotExists());
      }
      if (hasReplaceGraph()) {
        hash = (37 * hash) + REPLACE_GRAPH_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getReplaceGraph());
      }
      if (hasParentAndName()) {
        hash = (37 * hash) + PARENT_AND_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getParentAndName().hashCode();
      }
      if (hasGraphType()) {
        hash = (37 * hash) + GRAPH_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getGraphType().hashCode();
      }
      if (hasGraphSource()) {
        hash = (37 * hash) + GRAPH_SOURCE_FIELD_NUMBER;
        hash = (53 * hash) + getGraphSource().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ast.CatalogStatements.CreateGraphStatement parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ast.CatalogStatements.CreateGraphStatement parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ast.CatalogStatements.CreateGraphStatement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ast.CatalogStatements.CreateGraphStatement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ast.CatalogStatements.CreateGraphStatement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ast.CatalogStatements.CreateGraphStatement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ast.CatalogStatements.CreateGraphStatement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ast.CatalogStatements.CreateGraphStatement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ast.CatalogStatements.CreateGraphStatement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ast.CatalogStatements.CreateGraphStatement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ast.CatalogStatements.CreateGraphStatement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ast.CatalogStatements.CreateGraphStatement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ast.CatalogStatements.CreateGraphStatement prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ast.CreateGraphStatement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ast.CreateGraphStatement)
        ast.CatalogStatements.CreateGraphStatementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ast.CatalogStatements.internal_static_ast_CreateGraphStatement_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ast.CatalogStatements.internal_static_ast_CreateGraphStatement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ast.CatalogStatements.CreateGraphStatement.class, ast.CatalogStatements.CreateGraphStatement.Builder.class);
      }

      // Construct using ast.CatalogStatements.CreateGraphStatement.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getParentAndNameFieldBuilder();
          getGraphTypeFieldBuilder();
          getGraphSourceFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        ifNotExists_ = false;
        replaceGraph_ = false;
        parentAndName_ = null;
        if (parentAndNameBuilder_ != null) {
          parentAndNameBuilder_.dispose();
          parentAndNameBuilder_ = null;
        }
        graphType_ = null;
        if (graphTypeBuilder_ != null) {
          graphTypeBuilder_.dispose();
          graphTypeBuilder_ = null;
        }
        graphSource_ = null;
        if (graphSourceBuilder_ != null) {
          graphSourceBuilder_.dispose();
          graphSourceBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ast.CatalogStatements.internal_static_ast_CreateGraphStatement_descriptor;
      }

      @java.lang.Override
      public ast.CatalogStatements.CreateGraphStatement getDefaultInstanceForType() {
        return ast.CatalogStatements.CreateGraphStatement.getDefaultInstance();
      }

      @java.lang.Override
      public ast.CatalogStatements.CreateGraphStatement build() {
        ast.CatalogStatements.CreateGraphStatement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ast.CatalogStatements.CreateGraphStatement buildPartial() {
        ast.CatalogStatements.CreateGraphStatement result = new ast.CatalogStatements.CreateGraphStatement(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ast.CatalogStatements.CreateGraphStatement result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.ifNotExists_ = ifNotExists_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.replaceGraph_ = replaceGraph_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.parentAndName_ = parentAndNameBuilder_ == null
              ? parentAndName_
              : parentAndNameBuilder_.build();
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.graphType_ = graphTypeBuilder_ == null
              ? graphType_
              : graphTypeBuilder_.build();
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.graphSource_ = graphSourceBuilder_ == null
              ? graphSource_
              : graphSourceBuilder_.build();
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ast.CatalogStatements.CreateGraphStatement) {
          return mergeFrom((ast.CatalogStatements.CreateGraphStatement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ast.CatalogStatements.CreateGraphStatement other) {
        if (other == ast.CatalogStatements.CreateGraphStatement.getDefaultInstance()) return this;
        if (other.hasIfNotExists()) {
          setIfNotExists(other.getIfNotExists());
        }
        if (other.hasReplaceGraph()) {
          setReplaceGraph(other.getReplaceGraph());
        }
        if (other.hasParentAndName()) {
          mergeParentAndName(other.getParentAndName());
        }
        if (other.hasGraphType()) {
          mergeGraphType(other.getGraphType());
        }
        if (other.hasGraphSource()) {
          mergeGraphSource(other.getGraphSource());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                ifNotExists_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                replaceGraph_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                input.readMessage(
                    getParentAndNameFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getGraphTypeFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    getGraphSourceFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean ifNotExists_ ;
      /**
       * <code>optional bool if_not_exists = 1;</code>
       * @return Whether the ifNotExists field is set.
       */
      @java.lang.Override
      public boolean hasIfNotExists() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bool if_not_exists = 1;</code>
       * @return The ifNotExists.
       */
      @java.lang.Override
      public boolean getIfNotExists() {
        return ifNotExists_;
      }
      /**
       * <code>optional bool if_not_exists = 1;</code>
       * @param value The ifNotExists to set.
       * @return This builder for chaining.
       */
      public Builder setIfNotExists(boolean value) {

        ifNotExists_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool if_not_exists = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIfNotExists() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ifNotExists_ = false;
        onChanged();
        return this;
      }

      private boolean replaceGraph_ ;
      /**
       * <code>optional bool replace_graph = 2;</code>
       * @return Whether the replaceGraph field is set.
       */
      @java.lang.Override
      public boolean hasReplaceGraph() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bool replace_graph = 2;</code>
       * @return The replaceGraph.
       */
      @java.lang.Override
      public boolean getReplaceGraph() {
        return replaceGraph_;
      }
      /**
       * <code>optional bool replace_graph = 2;</code>
       * @param value The replaceGraph to set.
       * @return This builder for chaining.
       */
      public Builder setReplaceGraph(boolean value) {

        replaceGraph_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool replace_graph = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearReplaceGraph() {
        bitField0_ = (bitField0_ & ~0x00000002);
        replaceGraph_ = false;
        onChanged();
        return this;
      }

      private ast.Catalog.CatalogParentAndName parentAndName_;
      private com.google.protobuf.SingleFieldBuilder<
          ast.Catalog.CatalogParentAndName, ast.Catalog.CatalogParentAndName.Builder, ast.Catalog.CatalogParentAndNameOrBuilder> parentAndNameBuilder_;
      /**
       * <code>.ast.CatalogParentAndName parent_and_name = 3;</code>
       * @return Whether the parentAndName field is set.
       */
      public boolean hasParentAndName() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.ast.CatalogParentAndName parent_and_name = 3;</code>
       * @return The parentAndName.
       */
      public ast.Catalog.CatalogParentAndName getParentAndName() {
        if (parentAndNameBuilder_ == null) {
          return parentAndName_ == null ? ast.Catalog.CatalogParentAndName.getDefaultInstance() : parentAndName_;
        } else {
          return parentAndNameBuilder_.getMessage();
        }
      }
      /**
       * <code>.ast.CatalogParentAndName parent_and_name = 3;</code>
       */
      public Builder setParentAndName(ast.Catalog.CatalogParentAndName value) {
        if (parentAndNameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          parentAndName_ = value;
        } else {
          parentAndNameBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.ast.CatalogParentAndName parent_and_name = 3;</code>
       */
      public Builder setParentAndName(
          ast.Catalog.CatalogParentAndName.Builder builderForValue) {
        if (parentAndNameBuilder_ == null) {
          parentAndName_ = builderForValue.build();
        } else {
          parentAndNameBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.ast.CatalogParentAndName parent_and_name = 3;</code>
       */
      public Builder mergeParentAndName(ast.Catalog.CatalogParentAndName value) {
        if (parentAndNameBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            parentAndName_ != null &&
            parentAndName_ != ast.Catalog.CatalogParentAndName.getDefaultInstance()) {
            getParentAndNameBuilder().mergeFrom(value);
          } else {
            parentAndName_ = value;
          }
        } else {
          parentAndNameBuilder_.mergeFrom(value);
        }
        if (parentAndName_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.ast.CatalogParentAndName parent_and_name = 3;</code>
       */
      public Builder clearParentAndName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        parentAndName_ = null;
        if (parentAndNameBuilder_ != null) {
          parentAndNameBuilder_.dispose();
          parentAndNameBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.ast.CatalogParentAndName parent_and_name = 3;</code>
       */
      public ast.Catalog.CatalogParentAndName.Builder getParentAndNameBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getParentAndNameFieldBuilder().getBuilder();
      }
      /**
       * <code>.ast.CatalogParentAndName parent_and_name = 3;</code>
       */
      public ast.Catalog.CatalogParentAndNameOrBuilder getParentAndNameOrBuilder() {
        if (parentAndNameBuilder_ != null) {
          return parentAndNameBuilder_.getMessageOrBuilder();
        } else {
          return parentAndName_ == null ?
              ast.Catalog.CatalogParentAndName.getDefaultInstance() : parentAndName_;
        }
      }
      /**
       * <code>.ast.CatalogParentAndName parent_and_name = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ast.Catalog.CatalogParentAndName, ast.Catalog.CatalogParentAndName.Builder, ast.Catalog.CatalogParentAndNameOrBuilder> 
          getParentAndNameFieldBuilder() {
        if (parentAndNameBuilder_ == null) {
          parentAndNameBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ast.Catalog.CatalogParentAndName, ast.Catalog.CatalogParentAndName.Builder, ast.Catalog.CatalogParentAndNameOrBuilder>(
                  getParentAndName(),
                  getParentForChildren(),
                  isClean());
          parentAndName_ = null;
        }
        return parentAndNameBuilder_;
      }

      private ast.GraphTypeOuterClass.GraphType graphType_;
      private com.google.protobuf.SingleFieldBuilder<
          ast.GraphTypeOuterClass.GraphType, ast.GraphTypeOuterClass.GraphType.Builder, ast.GraphTypeOuterClass.GraphTypeOrBuilder> graphTypeBuilder_;
      /**
       * <code>optional .ast.GraphType graph_type = 4;</code>
       * @return Whether the graphType field is set.
       */
      public boolean hasGraphType() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional .ast.GraphType graph_type = 4;</code>
       * @return The graphType.
       */
      public ast.GraphTypeOuterClass.GraphType getGraphType() {
        if (graphTypeBuilder_ == null) {
          return graphType_ == null ? ast.GraphTypeOuterClass.GraphType.getDefaultInstance() : graphType_;
        } else {
          return graphTypeBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ast.GraphType graph_type = 4;</code>
       */
      public Builder setGraphType(ast.GraphTypeOuterClass.GraphType value) {
        if (graphTypeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          graphType_ = value;
        } else {
          graphTypeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional .ast.GraphType graph_type = 4;</code>
       */
      public Builder setGraphType(
          ast.GraphTypeOuterClass.GraphType.Builder builderForValue) {
        if (graphTypeBuilder_ == null) {
          graphType_ = builderForValue.build();
        } else {
          graphTypeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional .ast.GraphType graph_type = 4;</code>
       */
      public Builder mergeGraphType(ast.GraphTypeOuterClass.GraphType value) {
        if (graphTypeBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            graphType_ != null &&
            graphType_ != ast.GraphTypeOuterClass.GraphType.getDefaultInstance()) {
            getGraphTypeBuilder().mergeFrom(value);
          } else {
            graphType_ = value;
          }
        } else {
          graphTypeBuilder_.mergeFrom(value);
        }
        if (graphType_ != null) {
          bitField0_ |= 0x00000008;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .ast.GraphType graph_type = 4;</code>
       */
      public Builder clearGraphType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        graphType_ = null;
        if (graphTypeBuilder_ != null) {
          graphTypeBuilder_.dispose();
          graphTypeBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .ast.GraphType graph_type = 4;</code>
       */
      public ast.GraphTypeOuterClass.GraphType.Builder getGraphTypeBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getGraphTypeFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ast.GraphType graph_type = 4;</code>
       */
      public ast.GraphTypeOuterClass.GraphTypeOrBuilder getGraphTypeOrBuilder() {
        if (graphTypeBuilder_ != null) {
          return graphTypeBuilder_.getMessageOrBuilder();
        } else {
          return graphType_ == null ?
              ast.GraphTypeOuterClass.GraphType.getDefaultInstance() : graphType_;
        }
      }
      /**
       * <code>optional .ast.GraphType graph_type = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ast.GraphTypeOuterClass.GraphType, ast.GraphTypeOuterClass.GraphType.Builder, ast.GraphTypeOuterClass.GraphTypeOrBuilder> 
          getGraphTypeFieldBuilder() {
        if (graphTypeBuilder_ == null) {
          graphTypeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ast.GraphTypeOuterClass.GraphType, ast.GraphTypeOuterClass.GraphType.Builder, ast.GraphTypeOuterClass.GraphTypeOrBuilder>(
                  getGraphType(),
                  getParentForChildren(),
                  isClean());
          graphType_ = null;
        }
        return graphTypeBuilder_;
      }

      private ast.GraphExpressionOuterClass.GraphExpression graphSource_;
      private com.google.protobuf.SingleFieldBuilder<
          ast.GraphExpressionOuterClass.GraphExpression, ast.GraphExpressionOuterClass.GraphExpression.Builder, ast.GraphExpressionOuterClass.GraphExpressionOrBuilder> graphSourceBuilder_;
      /**
       * <code>optional .ast.GraphExpression graph_source = 5;</code>
       * @return Whether the graphSource field is set.
       */
      public boolean hasGraphSource() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional .ast.GraphExpression graph_source = 5;</code>
       * @return The graphSource.
       */
      public ast.GraphExpressionOuterClass.GraphExpression getGraphSource() {
        if (graphSourceBuilder_ == null) {
          return graphSource_ == null ? ast.GraphExpressionOuterClass.GraphExpression.getDefaultInstance() : graphSource_;
        } else {
          return graphSourceBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .ast.GraphExpression graph_source = 5;</code>
       */
      public Builder setGraphSource(ast.GraphExpressionOuterClass.GraphExpression value) {
        if (graphSourceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          graphSource_ = value;
        } else {
          graphSourceBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional .ast.GraphExpression graph_source = 5;</code>
       */
      public Builder setGraphSource(
          ast.GraphExpressionOuterClass.GraphExpression.Builder builderForValue) {
        if (graphSourceBuilder_ == null) {
          graphSource_ = builderForValue.build();
        } else {
          graphSourceBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional .ast.GraphExpression graph_source = 5;</code>
       */
      public Builder mergeGraphSource(ast.GraphExpressionOuterClass.GraphExpression value) {
        if (graphSourceBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            graphSource_ != null &&
            graphSource_ != ast.GraphExpressionOuterClass.GraphExpression.getDefaultInstance()) {
            getGraphSourceBuilder().mergeFrom(value);
          } else {
            graphSource_ = value;
          }
        } else {
          graphSourceBuilder_.mergeFrom(value);
        }
        if (graphSource_ != null) {
          bitField0_ |= 0x00000010;
          onChanged();
        }
        return this;
      }
      /**
       * <code>optional .ast.GraphExpression graph_source = 5;</code>
       */
      public Builder clearGraphSource() {
        bitField0_ = (bitField0_ & ~0x00000010);
        graphSource_ = null;
        if (graphSourceBuilder_ != null) {
          graphSourceBuilder_.dispose();
          graphSourceBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>optional .ast.GraphExpression graph_source = 5;</code>
       */
      public ast.GraphExpressionOuterClass.GraphExpression.Builder getGraphSourceBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getGraphSourceFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .ast.GraphExpression graph_source = 5;</code>
       */
      public ast.GraphExpressionOuterClass.GraphExpressionOrBuilder getGraphSourceOrBuilder() {
        if (graphSourceBuilder_ != null) {
          return graphSourceBuilder_.getMessageOrBuilder();
        } else {
          return graphSource_ == null ?
              ast.GraphExpressionOuterClass.GraphExpression.getDefaultInstance() : graphSource_;
        }
      }
      /**
       * <code>optional .ast.GraphExpression graph_source = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ast.GraphExpressionOuterClass.GraphExpression, ast.GraphExpressionOuterClass.GraphExpression.Builder, ast.GraphExpressionOuterClass.GraphExpressionOrBuilder> 
          getGraphSourceFieldBuilder() {
        if (graphSourceBuilder_ == null) {
          graphSourceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ast.GraphExpressionOuterClass.GraphExpression, ast.GraphExpressionOuterClass.GraphExpression.Builder, ast.GraphExpressionOuterClass.GraphExpressionOrBuilder>(
                  getGraphSource(),
                  getParentForChildren(),
                  isClean());
          graphSource_ = null;
        }
        return graphSourceBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ast.CreateGraphStatement)
    }

    // @@protoc_insertion_point(class_scope:ast.CreateGraphStatement)
    private static final ast.CatalogStatements.CreateGraphStatement DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ast.CatalogStatements.CreateGraphStatement();
    }

    public static ast.CatalogStatements.CreateGraphStatement getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreateGraphStatement>
        PARSER = new com.google.protobuf.AbstractParser<CreateGraphStatement>() {
      @java.lang.Override
      public CreateGraphStatement parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CreateGraphStatement> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreateGraphStatement> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ast.CatalogStatements.CreateGraphStatement getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DropGraphStatementOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ast.DropGraphStatement)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool if_exists = 1;</code>
     * @return Whether the ifExists field is set.
     */
    boolean hasIfExists();
    /**
     * <code>optional bool if_exists = 1;</code>
     * @return The ifExists.
     */
    boolean getIfExists();

    /**
     * <code>.ast.CatalogParentAndName parent_and_name = 2;</code>
     * @return Whether the parentAndName field is set.
     */
    boolean hasParentAndName();
    /**
     * <code>.ast.CatalogParentAndName parent_and_name = 2;</code>
     * @return The parentAndName.
     */
    ast.Catalog.CatalogParentAndName getParentAndName();
    /**
     * <code>.ast.CatalogParentAndName parent_and_name = 2;</code>
     */
    ast.Catalog.CatalogParentAndNameOrBuilder getParentAndNameOrBuilder();
  }
  /**
   * Protobuf type {@code ast.DropGraphStatement}
   */
  public static final class DropGraphStatement extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ast.DropGraphStatement)
      DropGraphStatementOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        DropGraphStatement.class.getName());
    }
    // Use DropGraphStatement.newBuilder() to construct.
    private DropGraphStatement(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private DropGraphStatement() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ast.CatalogStatements.internal_static_ast_DropGraphStatement_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ast.CatalogStatements.internal_static_ast_DropGraphStatement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ast.CatalogStatements.DropGraphStatement.class, ast.CatalogStatements.DropGraphStatement.Builder.class);
    }

    private int bitField0_;
    public static final int IF_EXISTS_FIELD_NUMBER = 1;
    private boolean ifExists_ = false;
    /**
     * <code>optional bool if_exists = 1;</code>
     * @return Whether the ifExists field is set.
     */
    @java.lang.Override
    public boolean hasIfExists() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bool if_exists = 1;</code>
     * @return The ifExists.
     */
    @java.lang.Override
    public boolean getIfExists() {
      return ifExists_;
    }

    public static final int PARENT_AND_NAME_FIELD_NUMBER = 2;
    private ast.Catalog.CatalogParentAndName parentAndName_;
    /**
     * <code>.ast.CatalogParentAndName parent_and_name = 2;</code>
     * @return Whether the parentAndName field is set.
     */
    @java.lang.Override
    public boolean hasParentAndName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.ast.CatalogParentAndName parent_and_name = 2;</code>
     * @return The parentAndName.
     */
    @java.lang.Override
    public ast.Catalog.CatalogParentAndName getParentAndName() {
      return parentAndName_ == null ? ast.Catalog.CatalogParentAndName.getDefaultInstance() : parentAndName_;
    }
    /**
     * <code>.ast.CatalogParentAndName parent_and_name = 2;</code>
     */
    @java.lang.Override
    public ast.Catalog.CatalogParentAndNameOrBuilder getParentAndNameOrBuilder() {
      return parentAndName_ == null ? ast.Catalog.CatalogParentAndName.getDefaultInstance() : parentAndName_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(1, ifExists_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getParentAndName());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, ifExists_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getParentAndName());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ast.CatalogStatements.DropGraphStatement)) {
        return super.equals(obj);
      }
      ast.CatalogStatements.DropGraphStatement other = (ast.CatalogStatements.DropGraphStatement) obj;

      if (hasIfExists() != other.hasIfExists()) return false;
      if (hasIfExists()) {
        if (getIfExists()
            != other.getIfExists()) return false;
      }
      if (hasParentAndName() != other.hasParentAndName()) return false;
      if (hasParentAndName()) {
        if (!getParentAndName()
            .equals(other.getParentAndName())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasIfExists()) {
        hash = (37 * hash) + IF_EXISTS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIfExists());
      }
      if (hasParentAndName()) {
        hash = (37 * hash) + PARENT_AND_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getParentAndName().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ast.CatalogStatements.DropGraphStatement parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ast.CatalogStatements.DropGraphStatement parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ast.CatalogStatements.DropGraphStatement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ast.CatalogStatements.DropGraphStatement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ast.CatalogStatements.DropGraphStatement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ast.CatalogStatements.DropGraphStatement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ast.CatalogStatements.DropGraphStatement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ast.CatalogStatements.DropGraphStatement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ast.CatalogStatements.DropGraphStatement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ast.CatalogStatements.DropGraphStatement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ast.CatalogStatements.DropGraphStatement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ast.CatalogStatements.DropGraphStatement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ast.CatalogStatements.DropGraphStatement prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ast.DropGraphStatement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ast.DropGraphStatement)
        ast.CatalogStatements.DropGraphStatementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ast.CatalogStatements.internal_static_ast_DropGraphStatement_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ast.CatalogStatements.internal_static_ast_DropGraphStatement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ast.CatalogStatements.DropGraphStatement.class, ast.CatalogStatements.DropGraphStatement.Builder.class);
      }

      // Construct using ast.CatalogStatements.DropGraphStatement.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getParentAndNameFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        ifExists_ = false;
        parentAndName_ = null;
        if (parentAndNameBuilder_ != null) {
          parentAndNameBuilder_.dispose();
          parentAndNameBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ast.CatalogStatements.internal_static_ast_DropGraphStatement_descriptor;
      }

      @java.lang.Override
      public ast.CatalogStatements.DropGraphStatement getDefaultInstanceForType() {
        return ast.CatalogStatements.DropGraphStatement.getDefaultInstance();
      }

      @java.lang.Override
      public ast.CatalogStatements.DropGraphStatement build() {
        ast.CatalogStatements.DropGraphStatement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ast.CatalogStatements.DropGraphStatement buildPartial() {
        ast.CatalogStatements.DropGraphStatement result = new ast.CatalogStatements.DropGraphStatement(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ast.CatalogStatements.DropGraphStatement result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.ifExists_ = ifExists_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.parentAndName_ = parentAndNameBuilder_ == null
              ? parentAndName_
              : parentAndNameBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ast.CatalogStatements.DropGraphStatement) {
          return mergeFrom((ast.CatalogStatements.DropGraphStatement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ast.CatalogStatements.DropGraphStatement other) {
        if (other == ast.CatalogStatements.DropGraphStatement.getDefaultInstance()) return this;
        if (other.hasIfExists()) {
          setIfExists(other.getIfExists());
        }
        if (other.hasParentAndName()) {
          mergeParentAndName(other.getParentAndName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                ifExists_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getParentAndNameFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean ifExists_ ;
      /**
       * <code>optional bool if_exists = 1;</code>
       * @return Whether the ifExists field is set.
       */
      @java.lang.Override
      public boolean hasIfExists() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bool if_exists = 1;</code>
       * @return The ifExists.
       */
      @java.lang.Override
      public boolean getIfExists() {
        return ifExists_;
      }
      /**
       * <code>optional bool if_exists = 1;</code>
       * @param value The ifExists to set.
       * @return This builder for chaining.
       */
      public Builder setIfExists(boolean value) {

        ifExists_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool if_exists = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIfExists() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ifExists_ = false;
        onChanged();
        return this;
      }

      private ast.Catalog.CatalogParentAndName parentAndName_;
      private com.google.protobuf.SingleFieldBuilder<
          ast.Catalog.CatalogParentAndName, ast.Catalog.CatalogParentAndName.Builder, ast.Catalog.CatalogParentAndNameOrBuilder> parentAndNameBuilder_;
      /**
       * <code>.ast.CatalogParentAndName parent_and_name = 2;</code>
       * @return Whether the parentAndName field is set.
       */
      public boolean hasParentAndName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.ast.CatalogParentAndName parent_and_name = 2;</code>
       * @return The parentAndName.
       */
      public ast.Catalog.CatalogParentAndName getParentAndName() {
        if (parentAndNameBuilder_ == null) {
          return parentAndName_ == null ? ast.Catalog.CatalogParentAndName.getDefaultInstance() : parentAndName_;
        } else {
          return parentAndNameBuilder_.getMessage();
        }
      }
      /**
       * <code>.ast.CatalogParentAndName parent_and_name = 2;</code>
       */
      public Builder setParentAndName(ast.Catalog.CatalogParentAndName value) {
        if (parentAndNameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          parentAndName_ = value;
        } else {
          parentAndNameBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.ast.CatalogParentAndName parent_and_name = 2;</code>
       */
      public Builder setParentAndName(
          ast.Catalog.CatalogParentAndName.Builder builderForValue) {
        if (parentAndNameBuilder_ == null) {
          parentAndName_ = builderForValue.build();
        } else {
          parentAndNameBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.ast.CatalogParentAndName parent_and_name = 2;</code>
       */
      public Builder mergeParentAndName(ast.Catalog.CatalogParentAndName value) {
        if (parentAndNameBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            parentAndName_ != null &&
            parentAndName_ != ast.Catalog.CatalogParentAndName.getDefaultInstance()) {
            getParentAndNameBuilder().mergeFrom(value);
          } else {
            parentAndName_ = value;
          }
        } else {
          parentAndNameBuilder_.mergeFrom(value);
        }
        if (parentAndName_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.ast.CatalogParentAndName parent_and_name = 2;</code>
       */
      public Builder clearParentAndName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        parentAndName_ = null;
        if (parentAndNameBuilder_ != null) {
          parentAndNameBuilder_.dispose();
          parentAndNameBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.ast.CatalogParentAndName parent_and_name = 2;</code>
       */
      public ast.Catalog.CatalogParentAndName.Builder getParentAndNameBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getParentAndNameFieldBuilder().getBuilder();
      }
      /**
       * <code>.ast.CatalogParentAndName parent_and_name = 2;</code>
       */
      public ast.Catalog.CatalogParentAndNameOrBuilder getParentAndNameOrBuilder() {
        if (parentAndNameBuilder_ != null) {
          return parentAndNameBuilder_.getMessageOrBuilder();
        } else {
          return parentAndName_ == null ?
              ast.Catalog.CatalogParentAndName.getDefaultInstance() : parentAndName_;
        }
      }
      /**
       * <code>.ast.CatalogParentAndName parent_and_name = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ast.Catalog.CatalogParentAndName, ast.Catalog.CatalogParentAndName.Builder, ast.Catalog.CatalogParentAndNameOrBuilder> 
          getParentAndNameFieldBuilder() {
        if (parentAndNameBuilder_ == null) {
          parentAndNameBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ast.Catalog.CatalogParentAndName, ast.Catalog.CatalogParentAndName.Builder, ast.Catalog.CatalogParentAndNameOrBuilder>(
                  getParentAndName(),
                  getParentForChildren(),
                  isClean());
          parentAndName_ = null;
        }
        return parentAndNameBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ast.DropGraphStatement)
    }

    // @@protoc_insertion_point(class_scope:ast.DropGraphStatement)
    private static final ast.CatalogStatements.DropGraphStatement DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ast.CatalogStatements.DropGraphStatement();
    }

    public static ast.CatalogStatements.DropGraphStatement getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DropGraphStatement>
        PARSER = new com.google.protobuf.AbstractParser<DropGraphStatement>() {
      @java.lang.Override
      public DropGraphStatement parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DropGraphStatement> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DropGraphStatement> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ast.CatalogStatements.DropGraphStatement getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ast_CreateGraphStatement_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ast_CreateGraphStatement_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ast_DropGraphStatement_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ast_DropGraphStatement_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030catalog_statements.proto\022\003ast\032\rcatalog" +
      ".proto\032\020graph_type.proto\032\026graph_expressi" +
      "on.proto\"\240\002\n\024CreateGraphStatement\022\032\n\rif_" +
      "not_exists\030\001 \001(\010H\000\210\001\001\022\032\n\rreplace_graph\030\002" +
      " \001(\010H\001\210\001\001\0222\n\017parent_and_name\030\003 \001(\0132\031.ast" +
      ".CatalogParentAndName\022\'\n\ngraph_type\030\004 \001(" +
      "\0132\016.ast.GraphTypeH\002\210\001\001\022/\n\014graph_source\030\005" +
      " \001(\0132\024.ast.GraphExpressionH\003\210\001\001B\020\n\016_if_n" +
      "ot_existsB\020\n\016_replace_graphB\r\n\013_graph_ty" +
      "peB\017\n\r_graph_source\"n\n\022DropGraphStatemen" +
      "t\022\026\n\tif_exists\030\001 \001(\010H\000\210\001\001\0222\n\017parent_and_" +
      "name\030\002 \001(\0132\031.ast.CatalogParentAndNameB\014\n" +
      "\n_if_existsB\006Z\004/astb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ast.Catalog.getDescriptor(),
          ast.GraphTypeOuterClass.getDescriptor(),
          ast.GraphExpressionOuterClass.getDescriptor(),
        });
    internal_static_ast_CreateGraphStatement_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ast_CreateGraphStatement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ast_CreateGraphStatement_descriptor,
        new java.lang.String[] { "IfNotExists", "ReplaceGraph", "ParentAndName", "GraphType", "GraphSource", });
    internal_static_ast_DropGraphStatement_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ast_DropGraphStatement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ast_DropGraphStatement_descriptor,
        new java.lang.String[] { "IfExists", "ParentAndName", });
    descriptor.resolveAllFeaturesImmutable();
    ast.Catalog.getDescriptor();
    ast.GraphTypeOuterClass.getDescriptor();
    ast.GraphExpressionOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
