// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: composite_query_statement.proto
// Protobuf Java Version: 4.29.3

package ast;

public final class CompositeQueryStatementOuterClass {
  private CompositeQueryStatementOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      CompositeQueryStatementOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CompositeQueryStatementOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ast.CompositeQueryStatement)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code ast.CompositeQueryStatement}
   */
  public static final class CompositeQueryStatement extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ast.CompositeQueryStatement)
      CompositeQueryStatementOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        CompositeQueryStatement.class.getName());
    }
    // Use CompositeQueryStatement.newBuilder() to construct.
    private CompositeQueryStatement(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CompositeQueryStatement() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ast.CompositeQueryStatementOuterClass.internal_static_ast_CompositeQueryStatement_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ast.CompositeQueryStatementOuterClass.internal_static_ast_CompositeQueryStatement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ast.CompositeQueryStatementOuterClass.CompositeQueryStatement.class, ast.CompositeQueryStatementOuterClass.CompositeQueryStatement.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ast.CompositeQueryStatementOuterClass.CompositeQueryStatement)) {
        return super.equals(obj);
      }
      ast.CompositeQueryStatementOuterClass.CompositeQueryStatement other = (ast.CompositeQueryStatementOuterClass.CompositeQueryStatement) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ast.CompositeQueryStatementOuterClass.CompositeQueryStatement parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ast.CompositeQueryStatementOuterClass.CompositeQueryStatement parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ast.CompositeQueryStatementOuterClass.CompositeQueryStatement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ast.CompositeQueryStatementOuterClass.CompositeQueryStatement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ast.CompositeQueryStatementOuterClass.CompositeQueryStatement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ast.CompositeQueryStatementOuterClass.CompositeQueryStatement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ast.CompositeQueryStatementOuterClass.CompositeQueryStatement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ast.CompositeQueryStatementOuterClass.CompositeQueryStatement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ast.CompositeQueryStatementOuterClass.CompositeQueryStatement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ast.CompositeQueryStatementOuterClass.CompositeQueryStatement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ast.CompositeQueryStatementOuterClass.CompositeQueryStatement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ast.CompositeQueryStatementOuterClass.CompositeQueryStatement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ast.CompositeQueryStatementOuterClass.CompositeQueryStatement prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ast.CompositeQueryStatement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ast.CompositeQueryStatement)
        ast.CompositeQueryStatementOuterClass.CompositeQueryStatementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ast.CompositeQueryStatementOuterClass.internal_static_ast_CompositeQueryStatement_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ast.CompositeQueryStatementOuterClass.internal_static_ast_CompositeQueryStatement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ast.CompositeQueryStatementOuterClass.CompositeQueryStatement.class, ast.CompositeQueryStatementOuterClass.CompositeQueryStatement.Builder.class);
      }

      // Construct using ast.CompositeQueryStatementOuterClass.CompositeQueryStatement.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ast.CompositeQueryStatementOuterClass.internal_static_ast_CompositeQueryStatement_descriptor;
      }

      @java.lang.Override
      public ast.CompositeQueryStatementOuterClass.CompositeQueryStatement getDefaultInstanceForType() {
        return ast.CompositeQueryStatementOuterClass.CompositeQueryStatement.getDefaultInstance();
      }

      @java.lang.Override
      public ast.CompositeQueryStatementOuterClass.CompositeQueryStatement build() {
        ast.CompositeQueryStatementOuterClass.CompositeQueryStatement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ast.CompositeQueryStatementOuterClass.CompositeQueryStatement buildPartial() {
        ast.CompositeQueryStatementOuterClass.CompositeQueryStatement result = new ast.CompositeQueryStatementOuterClass.CompositeQueryStatement(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ast.CompositeQueryStatementOuterClass.CompositeQueryStatement) {
          return mergeFrom((ast.CompositeQueryStatementOuterClass.CompositeQueryStatement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ast.CompositeQueryStatementOuterClass.CompositeQueryStatement other) {
        if (other == ast.CompositeQueryStatementOuterClass.CompositeQueryStatement.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ast.CompositeQueryStatement)
    }

    // @@protoc_insertion_point(class_scope:ast.CompositeQueryStatement)
    private static final ast.CompositeQueryStatementOuterClass.CompositeQueryStatement DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ast.CompositeQueryStatementOuterClass.CompositeQueryStatement();
    }

    public static ast.CompositeQueryStatementOuterClass.CompositeQueryStatement getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CompositeQueryStatement>
        PARSER = new com.google.protobuf.AbstractParser<CompositeQueryStatement>() {
      @java.lang.Override
      public CompositeQueryStatement parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CompositeQueryStatement> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CompositeQueryStatement> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ast.CompositeQueryStatementOuterClass.CompositeQueryStatement getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QueryStatementOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ast.QueryStatement)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ast.MatchStatement match_statement = 1;</code>
     * @return Whether the matchStatement field is set.
     */
    boolean hasMatchStatement();
    /**
     * <code>.ast.MatchStatement match_statement = 1;</code>
     * @return The matchStatement.
     */
    ast.CompositeQueryStatementOuterClass.MatchStatement getMatchStatement();
    /**
     * <code>.ast.MatchStatement match_statement = 1;</code>
     */
    ast.CompositeQueryStatementOuterClass.MatchStatementOrBuilder getMatchStatementOrBuilder();

    ast.CompositeQueryStatementOuterClass.QueryStatement.TypeCase getTypeCase();
  }
  /**
   * Protobuf type {@code ast.QueryStatement}
   */
  public static final class QueryStatement extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ast.QueryStatement)
      QueryStatementOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        QueryStatement.class.getName());
    }
    // Use QueryStatement.newBuilder() to construct.
    private QueryStatement(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private QueryStatement() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ast.CompositeQueryStatementOuterClass.internal_static_ast_QueryStatement_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ast.CompositeQueryStatementOuterClass.internal_static_ast_QueryStatement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ast.CompositeQueryStatementOuterClass.QueryStatement.class, ast.CompositeQueryStatementOuterClass.QueryStatement.Builder.class);
    }

    private int typeCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object type_;
    public enum TypeCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      MATCH_STATEMENT(1),
      TYPE_NOT_SET(0);
      private final int value;
      private TypeCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static TypeCase valueOf(int value) {
        return forNumber(value);
      }

      public static TypeCase forNumber(int value) {
        switch (value) {
          case 1: return MATCH_STATEMENT;
          case 0: return TYPE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public TypeCase
    getTypeCase() {
      return TypeCase.forNumber(
          typeCase_);
    }

    public static final int MATCH_STATEMENT_FIELD_NUMBER = 1;
    /**
     * <code>.ast.MatchStatement match_statement = 1;</code>
     * @return Whether the matchStatement field is set.
     */
    @java.lang.Override
    public boolean hasMatchStatement() {
      return typeCase_ == 1;
    }
    /**
     * <code>.ast.MatchStatement match_statement = 1;</code>
     * @return The matchStatement.
     */
    @java.lang.Override
    public ast.CompositeQueryStatementOuterClass.MatchStatement getMatchStatement() {
      if (typeCase_ == 1) {
         return (ast.CompositeQueryStatementOuterClass.MatchStatement) type_;
      }
      return ast.CompositeQueryStatementOuterClass.MatchStatement.getDefaultInstance();
    }
    /**
     * <code>.ast.MatchStatement match_statement = 1;</code>
     */
    @java.lang.Override
    public ast.CompositeQueryStatementOuterClass.MatchStatementOrBuilder getMatchStatementOrBuilder() {
      if (typeCase_ == 1) {
         return (ast.CompositeQueryStatementOuterClass.MatchStatement) type_;
      }
      return ast.CompositeQueryStatementOuterClass.MatchStatement.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (typeCase_ == 1) {
        output.writeMessage(1, (ast.CompositeQueryStatementOuterClass.MatchStatement) type_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (typeCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, (ast.CompositeQueryStatementOuterClass.MatchStatement) type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ast.CompositeQueryStatementOuterClass.QueryStatement)) {
        return super.equals(obj);
      }
      ast.CompositeQueryStatementOuterClass.QueryStatement other = (ast.CompositeQueryStatementOuterClass.QueryStatement) obj;

      if (!getTypeCase().equals(other.getTypeCase())) return false;
      switch (typeCase_) {
        case 1:
          if (!getMatchStatement()
              .equals(other.getMatchStatement())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (typeCase_) {
        case 1:
          hash = (37 * hash) + MATCH_STATEMENT_FIELD_NUMBER;
          hash = (53 * hash) + getMatchStatement().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ast.CompositeQueryStatementOuterClass.QueryStatement parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ast.CompositeQueryStatementOuterClass.QueryStatement parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ast.CompositeQueryStatementOuterClass.QueryStatement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ast.CompositeQueryStatementOuterClass.QueryStatement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ast.CompositeQueryStatementOuterClass.QueryStatement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ast.CompositeQueryStatementOuterClass.QueryStatement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ast.CompositeQueryStatementOuterClass.QueryStatement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ast.CompositeQueryStatementOuterClass.QueryStatement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ast.CompositeQueryStatementOuterClass.QueryStatement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ast.CompositeQueryStatementOuterClass.QueryStatement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ast.CompositeQueryStatementOuterClass.QueryStatement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ast.CompositeQueryStatementOuterClass.QueryStatement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ast.CompositeQueryStatementOuterClass.QueryStatement prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ast.QueryStatement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ast.QueryStatement)
        ast.CompositeQueryStatementOuterClass.QueryStatementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ast.CompositeQueryStatementOuterClass.internal_static_ast_QueryStatement_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ast.CompositeQueryStatementOuterClass.internal_static_ast_QueryStatement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ast.CompositeQueryStatementOuterClass.QueryStatement.class, ast.CompositeQueryStatementOuterClass.QueryStatement.Builder.class);
      }

      // Construct using ast.CompositeQueryStatementOuterClass.QueryStatement.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (matchStatementBuilder_ != null) {
          matchStatementBuilder_.clear();
        }
        typeCase_ = 0;
        type_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ast.CompositeQueryStatementOuterClass.internal_static_ast_QueryStatement_descriptor;
      }

      @java.lang.Override
      public ast.CompositeQueryStatementOuterClass.QueryStatement getDefaultInstanceForType() {
        return ast.CompositeQueryStatementOuterClass.QueryStatement.getDefaultInstance();
      }

      @java.lang.Override
      public ast.CompositeQueryStatementOuterClass.QueryStatement build() {
        ast.CompositeQueryStatementOuterClass.QueryStatement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ast.CompositeQueryStatementOuterClass.QueryStatement buildPartial() {
        ast.CompositeQueryStatementOuterClass.QueryStatement result = new ast.CompositeQueryStatementOuterClass.QueryStatement(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(ast.CompositeQueryStatementOuterClass.QueryStatement result) {
        int from_bitField0_ = bitField0_;
      }

      private void buildPartialOneofs(ast.CompositeQueryStatementOuterClass.QueryStatement result) {
        result.typeCase_ = typeCase_;
        result.type_ = this.type_;
        if (typeCase_ == 1 &&
            matchStatementBuilder_ != null) {
          result.type_ = matchStatementBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ast.CompositeQueryStatementOuterClass.QueryStatement) {
          return mergeFrom((ast.CompositeQueryStatementOuterClass.QueryStatement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ast.CompositeQueryStatementOuterClass.QueryStatement other) {
        if (other == ast.CompositeQueryStatementOuterClass.QueryStatement.getDefaultInstance()) return this;
        switch (other.getTypeCase()) {
          case MATCH_STATEMENT: {
            mergeMatchStatement(other.getMatchStatement());
            break;
          }
          case TYPE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getMatchStatementFieldBuilder().getBuilder(),
                    extensionRegistry);
                typeCase_ = 1;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int typeCase_ = 0;
      private java.lang.Object type_;
      public TypeCase
          getTypeCase() {
        return TypeCase.forNumber(
            typeCase_);
      }

      public Builder clearType() {
        typeCase_ = 0;
        type_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private com.google.protobuf.SingleFieldBuilder<
          ast.CompositeQueryStatementOuterClass.MatchStatement, ast.CompositeQueryStatementOuterClass.MatchStatement.Builder, ast.CompositeQueryStatementOuterClass.MatchStatementOrBuilder> matchStatementBuilder_;
      /**
       * <code>.ast.MatchStatement match_statement = 1;</code>
       * @return Whether the matchStatement field is set.
       */
      @java.lang.Override
      public boolean hasMatchStatement() {
        return typeCase_ == 1;
      }
      /**
       * <code>.ast.MatchStatement match_statement = 1;</code>
       * @return The matchStatement.
       */
      @java.lang.Override
      public ast.CompositeQueryStatementOuterClass.MatchStatement getMatchStatement() {
        if (matchStatementBuilder_ == null) {
          if (typeCase_ == 1) {
            return (ast.CompositeQueryStatementOuterClass.MatchStatement) type_;
          }
          return ast.CompositeQueryStatementOuterClass.MatchStatement.getDefaultInstance();
        } else {
          if (typeCase_ == 1) {
            return matchStatementBuilder_.getMessage();
          }
          return ast.CompositeQueryStatementOuterClass.MatchStatement.getDefaultInstance();
        }
      }
      /**
       * <code>.ast.MatchStatement match_statement = 1;</code>
       */
      public Builder setMatchStatement(ast.CompositeQueryStatementOuterClass.MatchStatement value) {
        if (matchStatementBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          type_ = value;
          onChanged();
        } else {
          matchStatementBuilder_.setMessage(value);
        }
        typeCase_ = 1;
        return this;
      }
      /**
       * <code>.ast.MatchStatement match_statement = 1;</code>
       */
      public Builder setMatchStatement(
          ast.CompositeQueryStatementOuterClass.MatchStatement.Builder builderForValue) {
        if (matchStatementBuilder_ == null) {
          type_ = builderForValue.build();
          onChanged();
        } else {
          matchStatementBuilder_.setMessage(builderForValue.build());
        }
        typeCase_ = 1;
        return this;
      }
      /**
       * <code>.ast.MatchStatement match_statement = 1;</code>
       */
      public Builder mergeMatchStatement(ast.CompositeQueryStatementOuterClass.MatchStatement value) {
        if (matchStatementBuilder_ == null) {
          if (typeCase_ == 1 &&
              type_ != ast.CompositeQueryStatementOuterClass.MatchStatement.getDefaultInstance()) {
            type_ = ast.CompositeQueryStatementOuterClass.MatchStatement.newBuilder((ast.CompositeQueryStatementOuterClass.MatchStatement) type_)
                .mergeFrom(value).buildPartial();
          } else {
            type_ = value;
          }
          onChanged();
        } else {
          if (typeCase_ == 1) {
            matchStatementBuilder_.mergeFrom(value);
          } else {
            matchStatementBuilder_.setMessage(value);
          }
        }
        typeCase_ = 1;
        return this;
      }
      /**
       * <code>.ast.MatchStatement match_statement = 1;</code>
       */
      public Builder clearMatchStatement() {
        if (matchStatementBuilder_ == null) {
          if (typeCase_ == 1) {
            typeCase_ = 0;
            type_ = null;
            onChanged();
          }
        } else {
          if (typeCase_ == 1) {
            typeCase_ = 0;
            type_ = null;
          }
          matchStatementBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.ast.MatchStatement match_statement = 1;</code>
       */
      public ast.CompositeQueryStatementOuterClass.MatchStatement.Builder getMatchStatementBuilder() {
        return getMatchStatementFieldBuilder().getBuilder();
      }
      /**
       * <code>.ast.MatchStatement match_statement = 1;</code>
       */
      @java.lang.Override
      public ast.CompositeQueryStatementOuterClass.MatchStatementOrBuilder getMatchStatementOrBuilder() {
        if ((typeCase_ == 1) && (matchStatementBuilder_ != null)) {
          return matchStatementBuilder_.getMessageOrBuilder();
        } else {
          if (typeCase_ == 1) {
            return (ast.CompositeQueryStatementOuterClass.MatchStatement) type_;
          }
          return ast.CompositeQueryStatementOuterClass.MatchStatement.getDefaultInstance();
        }
      }
      /**
       * <code>.ast.MatchStatement match_statement = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ast.CompositeQueryStatementOuterClass.MatchStatement, ast.CompositeQueryStatementOuterClass.MatchStatement.Builder, ast.CompositeQueryStatementOuterClass.MatchStatementOrBuilder> 
          getMatchStatementFieldBuilder() {
        if (matchStatementBuilder_ == null) {
          if (!(typeCase_ == 1)) {
            type_ = ast.CompositeQueryStatementOuterClass.MatchStatement.getDefaultInstance();
          }
          matchStatementBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ast.CompositeQueryStatementOuterClass.MatchStatement, ast.CompositeQueryStatementOuterClass.MatchStatement.Builder, ast.CompositeQueryStatementOuterClass.MatchStatementOrBuilder>(
                  (ast.CompositeQueryStatementOuterClass.MatchStatement) type_,
                  getParentForChildren(),
                  isClean());
          type_ = null;
        }
        typeCase_ = 1;
        onChanged();
        return matchStatementBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ast.QueryStatement)
    }

    // @@protoc_insertion_point(class_scope:ast.QueryStatement)
    private static final ast.CompositeQueryStatementOuterClass.QueryStatement DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ast.CompositeQueryStatementOuterClass.QueryStatement();
    }

    public static ast.CompositeQueryStatementOuterClass.QueryStatement getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QueryStatement>
        PARSER = new com.google.protobuf.AbstractParser<QueryStatement>() {
      @java.lang.Override
      public QueryStatement parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<QueryStatement> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QueryStatement> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ast.CompositeQueryStatementOuterClass.QueryStatement getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MatchStatementOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ast.MatchStatement)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code ast.MatchStatement}
   */
  public static final class MatchStatement extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ast.MatchStatement)
      MatchStatementOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        MatchStatement.class.getName());
    }
    // Use MatchStatement.newBuilder() to construct.
    private MatchStatement(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MatchStatement() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ast.CompositeQueryStatementOuterClass.internal_static_ast_MatchStatement_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ast.CompositeQueryStatementOuterClass.internal_static_ast_MatchStatement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ast.CompositeQueryStatementOuterClass.MatchStatement.class, ast.CompositeQueryStatementOuterClass.MatchStatement.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ast.CompositeQueryStatementOuterClass.MatchStatement)) {
        return super.equals(obj);
      }
      ast.CompositeQueryStatementOuterClass.MatchStatement other = (ast.CompositeQueryStatementOuterClass.MatchStatement) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ast.CompositeQueryStatementOuterClass.MatchStatement parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ast.CompositeQueryStatementOuterClass.MatchStatement parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ast.CompositeQueryStatementOuterClass.MatchStatement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ast.CompositeQueryStatementOuterClass.MatchStatement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ast.CompositeQueryStatementOuterClass.MatchStatement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ast.CompositeQueryStatementOuterClass.MatchStatement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ast.CompositeQueryStatementOuterClass.MatchStatement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ast.CompositeQueryStatementOuterClass.MatchStatement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ast.CompositeQueryStatementOuterClass.MatchStatement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ast.CompositeQueryStatementOuterClass.MatchStatement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ast.CompositeQueryStatementOuterClass.MatchStatement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ast.CompositeQueryStatementOuterClass.MatchStatement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ast.CompositeQueryStatementOuterClass.MatchStatement prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ast.MatchStatement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ast.MatchStatement)
        ast.CompositeQueryStatementOuterClass.MatchStatementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ast.CompositeQueryStatementOuterClass.internal_static_ast_MatchStatement_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ast.CompositeQueryStatementOuterClass.internal_static_ast_MatchStatement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ast.CompositeQueryStatementOuterClass.MatchStatement.class, ast.CompositeQueryStatementOuterClass.MatchStatement.Builder.class);
      }

      // Construct using ast.CompositeQueryStatementOuterClass.MatchStatement.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ast.CompositeQueryStatementOuterClass.internal_static_ast_MatchStatement_descriptor;
      }

      @java.lang.Override
      public ast.CompositeQueryStatementOuterClass.MatchStatement getDefaultInstanceForType() {
        return ast.CompositeQueryStatementOuterClass.MatchStatement.getDefaultInstance();
      }

      @java.lang.Override
      public ast.CompositeQueryStatementOuterClass.MatchStatement build() {
        ast.CompositeQueryStatementOuterClass.MatchStatement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ast.CompositeQueryStatementOuterClass.MatchStatement buildPartial() {
        ast.CompositeQueryStatementOuterClass.MatchStatement result = new ast.CompositeQueryStatementOuterClass.MatchStatement(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ast.CompositeQueryStatementOuterClass.MatchStatement) {
          return mergeFrom((ast.CompositeQueryStatementOuterClass.MatchStatement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ast.CompositeQueryStatementOuterClass.MatchStatement other) {
        if (other == ast.CompositeQueryStatementOuterClass.MatchStatement.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ast.MatchStatement)
    }

    // @@protoc_insertion_point(class_scope:ast.MatchStatement)
    private static final ast.CompositeQueryStatementOuterClass.MatchStatement DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ast.CompositeQueryStatementOuterClass.MatchStatement();
    }

    public static ast.CompositeQueryStatementOuterClass.MatchStatement getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MatchStatement>
        PARSER = new com.google.protobuf.AbstractParser<MatchStatement>() {
      @java.lang.Override
      public MatchStatement parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MatchStatement> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MatchStatement> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ast.CompositeQueryStatementOuterClass.MatchStatement getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ast_CompositeQueryStatement_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ast_CompositeQueryStatement_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ast_QueryStatement_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ast_QueryStatement_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ast_MatchStatement_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ast_MatchStatement_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037composite_query_statement.proto\022\003ast\032!" +
      "google/protobuf/go_features.proto\"\031\n\027Com" +
      "positeQueryStatement\"H\n\016QueryStatement\022." +
      "\n\017match_statement\030\001 \001(\0132\023.ast.MatchState" +
      "mentH\000B\006\n\004type\"\020\n\016MatchStatementB\020Z\004/ast" +
      "\222\003\007\010\002\322>\002\020\003b\010editionsp\350\007"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pb.GoFeaturesOuterClass.getDescriptor(),
        });
    internal_static_ast_CompositeQueryStatement_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ast_CompositeQueryStatement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ast_CompositeQueryStatement_descriptor,
        new java.lang.String[] { });
    internal_static_ast_QueryStatement_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ast_QueryStatement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ast_QueryStatement_descriptor,
        new java.lang.String[] { "MatchStatement", "Type", });
    internal_static_ast_MatchStatement_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ast_MatchStatement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ast_MatchStatement_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
    pb.GoFeaturesOuterClass.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(pb.GoFeaturesOuterClass.go);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
