// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: procedure_specification.proto
// Protobuf Java Version: 4.29.3

package ast;

public final class ProcedureSpecificationOuterClass {
  private ProcedureSpecificationOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      ProcedureSpecificationOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProcedureSpecificationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ast.ProcedureSpecification)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * Todo
   * </pre>
   *
   * Protobuf type {@code ast.ProcedureSpecification}
   */
  public static final class ProcedureSpecification extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ast.ProcedureSpecification)
      ProcedureSpecificationOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        ProcedureSpecification.class.getName());
    }
    // Use ProcedureSpecification.newBuilder() to construct.
    private ProcedureSpecification(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ProcedureSpecification() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ast.ProcedureSpecificationOuterClass.internal_static_ast_ProcedureSpecification_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ast.ProcedureSpecificationOuterClass.internal_static_ast_ProcedureSpecification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ast.ProcedureSpecificationOuterClass.ProcedureSpecification.class, ast.ProcedureSpecificationOuterClass.ProcedureSpecification.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ast.ProcedureSpecificationOuterClass.ProcedureSpecification)) {
        return super.equals(obj);
      }
      ast.ProcedureSpecificationOuterClass.ProcedureSpecification other = (ast.ProcedureSpecificationOuterClass.ProcedureSpecification) obj;

      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ast.ProcedureSpecificationOuterClass.ProcedureSpecification parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ast.ProcedureSpecificationOuterClass.ProcedureSpecification parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ast.ProcedureSpecificationOuterClass.ProcedureSpecification parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ast.ProcedureSpecificationOuterClass.ProcedureSpecification parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ast.ProcedureSpecificationOuterClass.ProcedureSpecification parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ast.ProcedureSpecificationOuterClass.ProcedureSpecification parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ast.ProcedureSpecificationOuterClass.ProcedureSpecification parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ast.ProcedureSpecificationOuterClass.ProcedureSpecification parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ast.ProcedureSpecificationOuterClass.ProcedureSpecification parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ast.ProcedureSpecificationOuterClass.ProcedureSpecification parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ast.ProcedureSpecificationOuterClass.ProcedureSpecification parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ast.ProcedureSpecificationOuterClass.ProcedureSpecification parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ast.ProcedureSpecificationOuterClass.ProcedureSpecification prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Todo
     * </pre>
     *
     * Protobuf type {@code ast.ProcedureSpecification}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ast.ProcedureSpecification)
        ast.ProcedureSpecificationOuterClass.ProcedureSpecificationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ast.ProcedureSpecificationOuterClass.internal_static_ast_ProcedureSpecification_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ast.ProcedureSpecificationOuterClass.internal_static_ast_ProcedureSpecification_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ast.ProcedureSpecificationOuterClass.ProcedureSpecification.class, ast.ProcedureSpecificationOuterClass.ProcedureSpecification.Builder.class);
      }

      // Construct using ast.ProcedureSpecificationOuterClass.ProcedureSpecification.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ast.ProcedureSpecificationOuterClass.internal_static_ast_ProcedureSpecification_descriptor;
      }

      @java.lang.Override
      public ast.ProcedureSpecificationOuterClass.ProcedureSpecification getDefaultInstanceForType() {
        return ast.ProcedureSpecificationOuterClass.ProcedureSpecification.getDefaultInstance();
      }

      @java.lang.Override
      public ast.ProcedureSpecificationOuterClass.ProcedureSpecification build() {
        ast.ProcedureSpecificationOuterClass.ProcedureSpecification result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ast.ProcedureSpecificationOuterClass.ProcedureSpecification buildPartial() {
        ast.ProcedureSpecificationOuterClass.ProcedureSpecification result = new ast.ProcedureSpecificationOuterClass.ProcedureSpecification(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ast.ProcedureSpecificationOuterClass.ProcedureSpecification) {
          return mergeFrom((ast.ProcedureSpecificationOuterClass.ProcedureSpecification)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ast.ProcedureSpecificationOuterClass.ProcedureSpecification other) {
        if (other == ast.ProcedureSpecificationOuterClass.ProcedureSpecification.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ast.ProcedureSpecification)
    }

    // @@protoc_insertion_point(class_scope:ast.ProcedureSpecification)
    private static final ast.ProcedureSpecificationOuterClass.ProcedureSpecification DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ast.ProcedureSpecificationOuterClass.ProcedureSpecification();
    }

    public static ast.ProcedureSpecificationOuterClass.ProcedureSpecification getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProcedureSpecification>
        PARSER = new com.google.protobuf.AbstractParser<ProcedureSpecification>() {
      @java.lang.Override
      public ProcedureSpecification parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ProcedureSpecification> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProcedureSpecification> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ast.ProcedureSpecificationOuterClass.ProcedureSpecification getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ast_ProcedureSpecification_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ast_ProcedureSpecification_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035procedure_specification.proto\022\003ast\"\030\n\026" +
      "ProcedureSpecificationB%Z#github.com/mbu" +
      "rbidg/gkit-ast/go/astb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ast_ProcedureSpecification_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ast_ProcedureSpecification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ast_ProcedureSpecification_descriptor,
        new java.lang.String[] { });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
