// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: yield_clause.proto
// Protobuf Java Version: 4.29.3

package ast;

public final class YieldClauseOuterClass {
  private YieldClauseOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      YieldClauseOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface YieldClauseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ast.YieldClause)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
     */
    java.util.List<ast.YieldClauseOuterClass.YieldItem> 
        getYieldItemListList();
    /**
     * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
     */
    ast.YieldClauseOuterClass.YieldItem getYieldItemList(int index);
    /**
     * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
     */
    int getYieldItemListCount();
    /**
     * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
     */
    java.util.List<? extends ast.YieldClauseOuterClass.YieldItemOrBuilder> 
        getYieldItemListOrBuilderList();
    /**
     * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
     */
    ast.YieldClauseOuterClass.YieldItemOrBuilder getYieldItemListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ast.YieldClause}
   */
  public static final class YieldClause extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ast.YieldClause)
      YieldClauseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        YieldClause.class.getName());
    }
    // Use YieldClause.newBuilder() to construct.
    private YieldClause(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private YieldClause() {
      yieldItemList_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ast.YieldClauseOuterClass.internal_static_ast_YieldClause_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ast.YieldClauseOuterClass.internal_static_ast_YieldClause_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ast.YieldClauseOuterClass.YieldClause.class, ast.YieldClauseOuterClass.YieldClause.Builder.class);
    }

    public static final int YIELD_ITEM_LIST_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<ast.YieldClauseOuterClass.YieldItem> yieldItemList_;
    /**
     * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
     */
    @java.lang.Override
    public java.util.List<ast.YieldClauseOuterClass.YieldItem> getYieldItemListList() {
      return yieldItemList_;
    }
    /**
     * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends ast.YieldClauseOuterClass.YieldItemOrBuilder> 
        getYieldItemListOrBuilderList() {
      return yieldItemList_;
    }
    /**
     * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
     */
    @java.lang.Override
    public int getYieldItemListCount() {
      return yieldItemList_.size();
    }
    /**
     * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
     */
    @java.lang.Override
    public ast.YieldClauseOuterClass.YieldItem getYieldItemList(int index) {
      return yieldItemList_.get(index);
    }
    /**
     * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
     */
    @java.lang.Override
    public ast.YieldClauseOuterClass.YieldItemOrBuilder getYieldItemListOrBuilder(
        int index) {
      return yieldItemList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < yieldItemList_.size(); i++) {
        output.writeMessage(1, yieldItemList_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < yieldItemList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, yieldItemList_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ast.YieldClauseOuterClass.YieldClause)) {
        return super.equals(obj);
      }
      ast.YieldClauseOuterClass.YieldClause other = (ast.YieldClauseOuterClass.YieldClause) obj;

      if (!getYieldItemListList()
          .equals(other.getYieldItemListList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getYieldItemListCount() > 0) {
        hash = (37 * hash) + YIELD_ITEM_LIST_FIELD_NUMBER;
        hash = (53 * hash) + getYieldItemListList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ast.YieldClauseOuterClass.YieldClause parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ast.YieldClauseOuterClass.YieldClause parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ast.YieldClauseOuterClass.YieldClause parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ast.YieldClauseOuterClass.YieldClause parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ast.YieldClauseOuterClass.YieldClause parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ast.YieldClauseOuterClass.YieldClause parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ast.YieldClauseOuterClass.YieldClause parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ast.YieldClauseOuterClass.YieldClause parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ast.YieldClauseOuterClass.YieldClause parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ast.YieldClauseOuterClass.YieldClause parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ast.YieldClauseOuterClass.YieldClause parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ast.YieldClauseOuterClass.YieldClause parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ast.YieldClauseOuterClass.YieldClause prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ast.YieldClause}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ast.YieldClause)
        ast.YieldClauseOuterClass.YieldClauseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ast.YieldClauseOuterClass.internal_static_ast_YieldClause_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ast.YieldClauseOuterClass.internal_static_ast_YieldClause_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ast.YieldClauseOuterClass.YieldClause.class, ast.YieldClauseOuterClass.YieldClause.Builder.class);
      }

      // Construct using ast.YieldClauseOuterClass.YieldClause.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (yieldItemListBuilder_ == null) {
          yieldItemList_ = java.util.Collections.emptyList();
        } else {
          yieldItemList_ = null;
          yieldItemListBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ast.YieldClauseOuterClass.internal_static_ast_YieldClause_descriptor;
      }

      @java.lang.Override
      public ast.YieldClauseOuterClass.YieldClause getDefaultInstanceForType() {
        return ast.YieldClauseOuterClass.YieldClause.getDefaultInstance();
      }

      @java.lang.Override
      public ast.YieldClauseOuterClass.YieldClause build() {
        ast.YieldClauseOuterClass.YieldClause result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ast.YieldClauseOuterClass.YieldClause buildPartial() {
        ast.YieldClauseOuterClass.YieldClause result = new ast.YieldClauseOuterClass.YieldClause(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(ast.YieldClauseOuterClass.YieldClause result) {
        if (yieldItemListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            yieldItemList_ = java.util.Collections.unmodifiableList(yieldItemList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.yieldItemList_ = yieldItemList_;
        } else {
          result.yieldItemList_ = yieldItemListBuilder_.build();
        }
      }

      private void buildPartial0(ast.YieldClauseOuterClass.YieldClause result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ast.YieldClauseOuterClass.YieldClause) {
          return mergeFrom((ast.YieldClauseOuterClass.YieldClause)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ast.YieldClauseOuterClass.YieldClause other) {
        if (other == ast.YieldClauseOuterClass.YieldClause.getDefaultInstance()) return this;
        if (yieldItemListBuilder_ == null) {
          if (!other.yieldItemList_.isEmpty()) {
            if (yieldItemList_.isEmpty()) {
              yieldItemList_ = other.yieldItemList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureYieldItemListIsMutable();
              yieldItemList_.addAll(other.yieldItemList_);
            }
            onChanged();
          }
        } else {
          if (!other.yieldItemList_.isEmpty()) {
            if (yieldItemListBuilder_.isEmpty()) {
              yieldItemListBuilder_.dispose();
              yieldItemListBuilder_ = null;
              yieldItemList_ = other.yieldItemList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              yieldItemListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getYieldItemListFieldBuilder() : null;
            } else {
              yieldItemListBuilder_.addAllMessages(other.yieldItemList_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                ast.YieldClauseOuterClass.YieldItem m =
                    input.readMessage(
                        ast.YieldClauseOuterClass.YieldItem.parser(),
                        extensionRegistry);
                if (yieldItemListBuilder_ == null) {
                  ensureYieldItemListIsMutable();
                  yieldItemList_.add(m);
                } else {
                  yieldItemListBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<ast.YieldClauseOuterClass.YieldItem> yieldItemList_ =
        java.util.Collections.emptyList();
      private void ensureYieldItemListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          yieldItemList_ = new java.util.ArrayList<ast.YieldClauseOuterClass.YieldItem>(yieldItemList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          ast.YieldClauseOuterClass.YieldItem, ast.YieldClauseOuterClass.YieldItem.Builder, ast.YieldClauseOuterClass.YieldItemOrBuilder> yieldItemListBuilder_;

      /**
       * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
       */
      public java.util.List<ast.YieldClauseOuterClass.YieldItem> getYieldItemListList() {
        if (yieldItemListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(yieldItemList_);
        } else {
          return yieldItemListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
       */
      public int getYieldItemListCount() {
        if (yieldItemListBuilder_ == null) {
          return yieldItemList_.size();
        } else {
          return yieldItemListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
       */
      public ast.YieldClauseOuterClass.YieldItem getYieldItemList(int index) {
        if (yieldItemListBuilder_ == null) {
          return yieldItemList_.get(index);
        } else {
          return yieldItemListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
       */
      public Builder setYieldItemList(
          int index, ast.YieldClauseOuterClass.YieldItem value) {
        if (yieldItemListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureYieldItemListIsMutable();
          yieldItemList_.set(index, value);
          onChanged();
        } else {
          yieldItemListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
       */
      public Builder setYieldItemList(
          int index, ast.YieldClauseOuterClass.YieldItem.Builder builderForValue) {
        if (yieldItemListBuilder_ == null) {
          ensureYieldItemListIsMutable();
          yieldItemList_.set(index, builderForValue.build());
          onChanged();
        } else {
          yieldItemListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
       */
      public Builder addYieldItemList(ast.YieldClauseOuterClass.YieldItem value) {
        if (yieldItemListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureYieldItemListIsMutable();
          yieldItemList_.add(value);
          onChanged();
        } else {
          yieldItemListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
       */
      public Builder addYieldItemList(
          int index, ast.YieldClauseOuterClass.YieldItem value) {
        if (yieldItemListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureYieldItemListIsMutable();
          yieldItemList_.add(index, value);
          onChanged();
        } else {
          yieldItemListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
       */
      public Builder addYieldItemList(
          ast.YieldClauseOuterClass.YieldItem.Builder builderForValue) {
        if (yieldItemListBuilder_ == null) {
          ensureYieldItemListIsMutable();
          yieldItemList_.add(builderForValue.build());
          onChanged();
        } else {
          yieldItemListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
       */
      public Builder addYieldItemList(
          int index, ast.YieldClauseOuterClass.YieldItem.Builder builderForValue) {
        if (yieldItemListBuilder_ == null) {
          ensureYieldItemListIsMutable();
          yieldItemList_.add(index, builderForValue.build());
          onChanged();
        } else {
          yieldItemListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
       */
      public Builder addAllYieldItemList(
          java.lang.Iterable<? extends ast.YieldClauseOuterClass.YieldItem> values) {
        if (yieldItemListBuilder_ == null) {
          ensureYieldItemListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, yieldItemList_);
          onChanged();
        } else {
          yieldItemListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
       */
      public Builder clearYieldItemList() {
        if (yieldItemListBuilder_ == null) {
          yieldItemList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          yieldItemListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
       */
      public Builder removeYieldItemList(int index) {
        if (yieldItemListBuilder_ == null) {
          ensureYieldItemListIsMutable();
          yieldItemList_.remove(index);
          onChanged();
        } else {
          yieldItemListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
       */
      public ast.YieldClauseOuterClass.YieldItem.Builder getYieldItemListBuilder(
          int index) {
        return getYieldItemListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
       */
      public ast.YieldClauseOuterClass.YieldItemOrBuilder getYieldItemListOrBuilder(
          int index) {
        if (yieldItemListBuilder_ == null) {
          return yieldItemList_.get(index);  } else {
          return yieldItemListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
       */
      public java.util.List<? extends ast.YieldClauseOuterClass.YieldItemOrBuilder> 
           getYieldItemListOrBuilderList() {
        if (yieldItemListBuilder_ != null) {
          return yieldItemListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(yieldItemList_);
        }
      }
      /**
       * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
       */
      public ast.YieldClauseOuterClass.YieldItem.Builder addYieldItemListBuilder() {
        return getYieldItemListFieldBuilder().addBuilder(
            ast.YieldClauseOuterClass.YieldItem.getDefaultInstance());
      }
      /**
       * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
       */
      public ast.YieldClauseOuterClass.YieldItem.Builder addYieldItemListBuilder(
          int index) {
        return getYieldItemListFieldBuilder().addBuilder(
            index, ast.YieldClauseOuterClass.YieldItem.getDefaultInstance());
      }
      /**
       * <code>repeated .ast.YieldItem yield_item_list = 1;</code>
       */
      public java.util.List<ast.YieldClauseOuterClass.YieldItem.Builder> 
           getYieldItemListBuilderList() {
        return getYieldItemListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ast.YieldClauseOuterClass.YieldItem, ast.YieldClauseOuterClass.YieldItem.Builder, ast.YieldClauseOuterClass.YieldItemOrBuilder> 
          getYieldItemListFieldBuilder() {
        if (yieldItemListBuilder_ == null) {
          yieldItemListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ast.YieldClauseOuterClass.YieldItem, ast.YieldClauseOuterClass.YieldItem.Builder, ast.YieldClauseOuterClass.YieldItemOrBuilder>(
                  yieldItemList_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          yieldItemList_ = null;
        }
        return yieldItemListBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ast.YieldClause)
    }

    // @@protoc_insertion_point(class_scope:ast.YieldClause)
    private static final ast.YieldClauseOuterClass.YieldClause DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ast.YieldClauseOuterClass.YieldClause();
    }

    public static ast.YieldClauseOuterClass.YieldClause getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<YieldClause>
        PARSER = new com.google.protobuf.AbstractParser<YieldClause>() {
      @java.lang.Override
      public YieldClause parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<YieldClause> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<YieldClause> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ast.YieldClauseOuterClass.YieldClause getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface YieldItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ast.YieldItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.ast.Identifier name = 1;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>.ast.Identifier name = 1;</code>
     * @return The name.
     */
    ast.Literals.Identifier getName();
    /**
     * <code>.ast.Identifier name = 1;</code>
     */
    ast.Literals.IdentifierOrBuilder getNameOrBuilder();

    /**
     * <code>.ast.Identifier alias = 2 [features = { ... }</code>
     * @return Whether the alias field is set.
     */
    boolean hasAlias();
    /**
     * <code>.ast.Identifier alias = 2 [features = { ... }</code>
     * @return The alias.
     */
    ast.Literals.Identifier getAlias();
    /**
     * <code>.ast.Identifier alias = 2 [features = { ... }</code>
     */
    ast.Literals.IdentifierOrBuilder getAliasOrBuilder();
  }
  /**
   * Protobuf type {@code ast.YieldItem}
   */
  public static final class YieldItem extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ast.YieldItem)
      YieldItemOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        YieldItem.class.getName());
    }
    // Use YieldItem.newBuilder() to construct.
    private YieldItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private YieldItem() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ast.YieldClauseOuterClass.internal_static_ast_YieldItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ast.YieldClauseOuterClass.internal_static_ast_YieldItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ast.YieldClauseOuterClass.YieldItem.class, ast.YieldClauseOuterClass.YieldItem.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private ast.Literals.Identifier name_;
    /**
     * <code>.ast.Identifier name = 1;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.ast.Identifier name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public ast.Literals.Identifier getName() {
      return name_ == null ? ast.Literals.Identifier.getDefaultInstance() : name_;
    }
    /**
     * <code>.ast.Identifier name = 1;</code>
     */
    @java.lang.Override
    public ast.Literals.IdentifierOrBuilder getNameOrBuilder() {
      return name_ == null ? ast.Literals.Identifier.getDefaultInstance() : name_;
    }

    public static final int ALIAS_FIELD_NUMBER = 2;
    private ast.Literals.Identifier alias_;
    /**
     * <code>.ast.Identifier alias = 2 [features = { ... }</code>
     * @return Whether the alias field is set.
     */
    @java.lang.Override
    public boolean hasAlias() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.ast.Identifier alias = 2 [features = { ... }</code>
     * @return The alias.
     */
    @java.lang.Override
    public ast.Literals.Identifier getAlias() {
      return alias_ == null ? ast.Literals.Identifier.getDefaultInstance() : alias_;
    }
    /**
     * <code>.ast.Identifier alias = 2 [features = { ... }</code>
     */
    @java.lang.Override
    public ast.Literals.IdentifierOrBuilder getAliasOrBuilder() {
      return alias_ == null ? ast.Literals.Identifier.getDefaultInstance() : alias_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getName());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getAlias());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getName());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getAlias());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ast.YieldClauseOuterClass.YieldItem)) {
        return super.equals(obj);
      }
      ast.YieldClauseOuterClass.YieldItem other = (ast.YieldClauseOuterClass.YieldItem) obj;

      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasAlias() != other.hasAlias()) return false;
      if (hasAlias()) {
        if (!getAlias()
            .equals(other.getAlias())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasAlias()) {
        hash = (37 * hash) + ALIAS_FIELD_NUMBER;
        hash = (53 * hash) + getAlias().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ast.YieldClauseOuterClass.YieldItem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ast.YieldClauseOuterClass.YieldItem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ast.YieldClauseOuterClass.YieldItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ast.YieldClauseOuterClass.YieldItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ast.YieldClauseOuterClass.YieldItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ast.YieldClauseOuterClass.YieldItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ast.YieldClauseOuterClass.YieldItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ast.YieldClauseOuterClass.YieldItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ast.YieldClauseOuterClass.YieldItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ast.YieldClauseOuterClass.YieldItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ast.YieldClauseOuterClass.YieldItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ast.YieldClauseOuterClass.YieldItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ast.YieldClauseOuterClass.YieldItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ast.YieldItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ast.YieldItem)
        ast.YieldClauseOuterClass.YieldItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ast.YieldClauseOuterClass.internal_static_ast_YieldItem_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ast.YieldClauseOuterClass.internal_static_ast_YieldItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ast.YieldClauseOuterClass.YieldItem.class, ast.YieldClauseOuterClass.YieldItem.Builder.class);
      }

      // Construct using ast.YieldClauseOuterClass.YieldItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getNameFieldBuilder();
          getAliasFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = null;
        if (nameBuilder_ != null) {
          nameBuilder_.dispose();
          nameBuilder_ = null;
        }
        alias_ = null;
        if (aliasBuilder_ != null) {
          aliasBuilder_.dispose();
          aliasBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ast.YieldClauseOuterClass.internal_static_ast_YieldItem_descriptor;
      }

      @java.lang.Override
      public ast.YieldClauseOuterClass.YieldItem getDefaultInstanceForType() {
        return ast.YieldClauseOuterClass.YieldItem.getDefaultInstance();
      }

      @java.lang.Override
      public ast.YieldClauseOuterClass.YieldItem build() {
        ast.YieldClauseOuterClass.YieldItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ast.YieldClauseOuterClass.YieldItem buildPartial() {
        ast.YieldClauseOuterClass.YieldItem result = new ast.YieldClauseOuterClass.YieldItem(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ast.YieldClauseOuterClass.YieldItem result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = nameBuilder_ == null
              ? name_
              : nameBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.alias_ = aliasBuilder_ == null
              ? alias_
              : aliasBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ast.YieldClauseOuterClass.YieldItem) {
          return mergeFrom((ast.YieldClauseOuterClass.YieldItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ast.YieldClauseOuterClass.YieldItem other) {
        if (other == ast.YieldClauseOuterClass.YieldItem.getDefaultInstance()) return this;
        if (other.hasName()) {
          mergeName(other.getName());
        }
        if (other.hasAlias()) {
          mergeAlias(other.getAlias());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getNameFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getAliasFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private ast.Literals.Identifier name_;
      private com.google.protobuf.SingleFieldBuilder<
          ast.Literals.Identifier, ast.Literals.Identifier.Builder, ast.Literals.IdentifierOrBuilder> nameBuilder_;
      /**
       * <code>.ast.Identifier name = 1;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.ast.Identifier name = 1;</code>
       * @return The name.
       */
      public ast.Literals.Identifier getName() {
        if (nameBuilder_ == null) {
          return name_ == null ? ast.Literals.Identifier.getDefaultInstance() : name_;
        } else {
          return nameBuilder_.getMessage();
        }
      }
      /**
       * <code>.ast.Identifier name = 1;</code>
       */
      public Builder setName(ast.Literals.Identifier value) {
        if (nameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          name_ = value;
        } else {
          nameBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.ast.Identifier name = 1;</code>
       */
      public Builder setName(
          ast.Literals.Identifier.Builder builderForValue) {
        if (nameBuilder_ == null) {
          name_ = builderForValue.build();
        } else {
          nameBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.ast.Identifier name = 1;</code>
       */
      public Builder mergeName(ast.Literals.Identifier value) {
        if (nameBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            name_ != null &&
            name_ != ast.Literals.Identifier.getDefaultInstance()) {
            getNameBuilder().mergeFrom(value);
          } else {
            name_ = value;
          }
        } else {
          nameBuilder_.mergeFrom(value);
        }
        if (name_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.ast.Identifier name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = null;
        if (nameBuilder_ != null) {
          nameBuilder_.dispose();
          nameBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.ast.Identifier name = 1;</code>
       */
      public ast.Literals.Identifier.Builder getNameBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getNameFieldBuilder().getBuilder();
      }
      /**
       * <code>.ast.Identifier name = 1;</code>
       */
      public ast.Literals.IdentifierOrBuilder getNameOrBuilder() {
        if (nameBuilder_ != null) {
          return nameBuilder_.getMessageOrBuilder();
        } else {
          return name_ == null ?
              ast.Literals.Identifier.getDefaultInstance() : name_;
        }
      }
      /**
       * <code>.ast.Identifier name = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ast.Literals.Identifier, ast.Literals.Identifier.Builder, ast.Literals.IdentifierOrBuilder> 
          getNameFieldBuilder() {
        if (nameBuilder_ == null) {
          nameBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ast.Literals.Identifier, ast.Literals.Identifier.Builder, ast.Literals.IdentifierOrBuilder>(
                  getName(),
                  getParentForChildren(),
                  isClean());
          name_ = null;
        }
        return nameBuilder_;
      }

      private ast.Literals.Identifier alias_;
      private com.google.protobuf.SingleFieldBuilder<
          ast.Literals.Identifier, ast.Literals.Identifier.Builder, ast.Literals.IdentifierOrBuilder> aliasBuilder_;
      /**
       * <code>.ast.Identifier alias = 2 [features = { ... }</code>
       * @return Whether the alias field is set.
       */
      public boolean hasAlias() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.ast.Identifier alias = 2 [features = { ... }</code>
       * @return The alias.
       */
      public ast.Literals.Identifier getAlias() {
        if (aliasBuilder_ == null) {
          return alias_ == null ? ast.Literals.Identifier.getDefaultInstance() : alias_;
        } else {
          return aliasBuilder_.getMessage();
        }
      }
      /**
       * <code>.ast.Identifier alias = 2 [features = { ... }</code>
       */
      public Builder setAlias(ast.Literals.Identifier value) {
        if (aliasBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          alias_ = value;
        } else {
          aliasBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.ast.Identifier alias = 2 [features = { ... }</code>
       */
      public Builder setAlias(
          ast.Literals.Identifier.Builder builderForValue) {
        if (aliasBuilder_ == null) {
          alias_ = builderForValue.build();
        } else {
          aliasBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.ast.Identifier alias = 2 [features = { ... }</code>
       */
      public Builder mergeAlias(ast.Literals.Identifier value) {
        if (aliasBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            alias_ != null &&
            alias_ != ast.Literals.Identifier.getDefaultInstance()) {
            getAliasBuilder().mergeFrom(value);
          } else {
            alias_ = value;
          }
        } else {
          aliasBuilder_.mergeFrom(value);
        }
        if (alias_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.ast.Identifier alias = 2 [features = { ... }</code>
       */
      public Builder clearAlias() {
        bitField0_ = (bitField0_ & ~0x00000002);
        alias_ = null;
        if (aliasBuilder_ != null) {
          aliasBuilder_.dispose();
          aliasBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.ast.Identifier alias = 2 [features = { ... }</code>
       */
      public ast.Literals.Identifier.Builder getAliasBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getAliasFieldBuilder().getBuilder();
      }
      /**
       * <code>.ast.Identifier alias = 2 [features = { ... }</code>
       */
      public ast.Literals.IdentifierOrBuilder getAliasOrBuilder() {
        if (aliasBuilder_ != null) {
          return aliasBuilder_.getMessageOrBuilder();
        } else {
          return alias_ == null ?
              ast.Literals.Identifier.getDefaultInstance() : alias_;
        }
      }
      /**
       * <code>.ast.Identifier alias = 2 [features = { ... }</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          ast.Literals.Identifier, ast.Literals.Identifier.Builder, ast.Literals.IdentifierOrBuilder> 
          getAliasFieldBuilder() {
        if (aliasBuilder_ == null) {
          aliasBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              ast.Literals.Identifier, ast.Literals.Identifier.Builder, ast.Literals.IdentifierOrBuilder>(
                  getAlias(),
                  getParentForChildren(),
                  isClean());
          alias_ = null;
        }
        return aliasBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ast.YieldItem)
    }

    // @@protoc_insertion_point(class_scope:ast.YieldItem)
    private static final ast.YieldClauseOuterClass.YieldItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ast.YieldClauseOuterClass.YieldItem();
    }

    public static ast.YieldClauseOuterClass.YieldItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<YieldItem>
        PARSER = new com.google.protobuf.AbstractParser<YieldItem>() {
      @java.lang.Override
      public YieldItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<YieldItem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<YieldItem> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ast.YieldClauseOuterClass.YieldItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ast_YieldClause_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ast_YieldClause_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ast_YieldItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ast_YieldItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022yield_clause.proto\022\003ast\032!google/protob" +
      "uf/go_features.proto\032\016literals.proto\"6\n\013" +
      "YieldClause\022\'\n\017yield_item_list\030\001 \003(\0132\016.a" +
      "st.YieldItem\"Q\n\tYieldItem\022\035\n\004name\030\001 \001(\0132" +
      "\017.ast.Identifier\022%\n\005alias\030\002 \001(\0132\017.ast.Id" +
      "entifierB\005\252\001\002\010\001B\020Z\004/ast\222\003\007\010\002\322>\002\020\003b\010editi" +
      "onsp\350\007"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          pb.GoFeaturesOuterClass.getDescriptor(),
          ast.Literals.getDescriptor(),
        });
    internal_static_ast_YieldClause_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ast_YieldClause_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ast_YieldClause_descriptor,
        new java.lang.String[] { "YieldItemList", });
    internal_static_ast_YieldItem_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ast_YieldItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ast_YieldItem_descriptor,
        new java.lang.String[] { "Name", "Alias", });
    descriptor.resolveAllFeaturesImmutable();
    pb.GoFeaturesOuterClass.getDescriptor();
    ast.Literals.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(pb.GoFeaturesOuterClass.go);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
